- docs/automation/circle-ci.md
- docs/automation/jenkins.md
- docs/automation/travis-ci.md
- docs/hosting/aws-s3.md
- docs/hosting/docker-nginx-letsencrypt.md
- docs/hosting/github-pages.md
- docs/hosting/linux-server.md
- mkdocs.yml
Basic documentation for automation (CircleCI, TravisCI, Jenkins) and hosting (GH Pages, AWS S3, Linux).
> Hosting and automation - fixes #15

- .circleci/config.yml
The CI configuration right now just downloads the master branch of this project and tests that. That's not useful - we need to be testing whatever has been changed in the PR. This is an attempt to accomplish that.
> Fix CI configuration so that new changes are actually tested

- .circleci/config.yml
- Gemfile
- Makefile
- tests/_config.yml
Decouple testing logic from CI service and put in a Makefile.
> Makefile approach

- _includes/footer.html
> Switch to a configurable twitter name

- docs/quick-start.md
> More correct keygen command and more details on getting key contents.

- docs/automation/github.md
- docs/quick-start.md
- mkdocs.yml
> Docs on GitHub and automated tests

- assets/css/default.scss
Fixes some issues with visibility of content in tables that were raised in issue #2
> Improvements to vision of table content in high contrast mode.

- _includes/assets/js/search.js
- _includes/search.html
- tests/features/Search.feature
* Fixes #81
* Allows Google Analytics to understand searches
* Also update tests in relevant places
> add q= to search query url

- docs/making-updates.md
> Provide documentation of data/metadata updates

- _layouts/indicator-json.html
> Avoid double-quotes in the manually-generated json files

- docs/quick-start.md
Some recommendations from myself following the Quick Start guide as a newcomer. I've included the updated ssh-keygen command and some notes on following the guide on a Mac.
> Update recommendations to Quick Start guide

- CHANGELOG.md
- docs/changelog.md
Tentative updates to changelog, depending on what makes it into the release.
> Changelog updates for 0.4.0

- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/plugins/leaflet.yearSlider.js
> Map - skip missing years in slider

- _layouts/reportingstatus.html
This should not be merged until [this pull-request](https://github.com/open-sdg/sdg-translations/pull/69) has been merged.
Fixes #113
> Translate the text 'Status by goal'

- docs/case-studies/armenia.md
- docs/community.md
This adds an approved case study for the Armenia platform, and links to it from the Community "who is using" page.
> Armenia case study

- tests/features/support/mink.js
This fixes a test to accommodate the latest markup changes.
> Fix CSS selector according to latest markup

- docs/case-studies/rwanda.md
- docs/community.md
- mkdocs.yml
@brockfanning Country case study for Rwanda
> Rwanda case study

- docs/changelog.md
We can add to this if we're sneaking anything else into the release. Anything I've missed?
> Release notes for 0.5.0

- _includes/assets/js/indicatorModel.js
@brockfanning can we also exclude the 'Unit measure' field please?
P.S. Am not getting the option to update this branch, but I can see it is 33 commits behind master.
> Exclude column 'Unit measure'

- docs/faq.md
@brockfanning are you happy with these example links and the reference to UK step-by-step guidance?
> FAQ: mapping update

- open-sdg.gemspec
> Gemspec file

- _includes/head.html
- _includes/scripts.html
> Update Bootstrap to 3.4.1

- _layouts/reportingstatus.html
This rounds the percentages on the reporting status page.
> Round the percentages for human-readable labels

- docs/faq.md
@AnnCorp Here's an [example](https://github.com/open-sdg/open-sdg/edit/Norric1Admin-patch-1/docs/faq.md) of how this would look - click 'Preview'.
Hold off on this until tomorrow, as the 3.4.2 embed is no longer live.
> FAQ: Update mapping and embedded content examples

- _includes/footer.html
- assets/css/default.scss
The links at the footer are now an unordered list (`<ul>`). I will also make a pull request on `sdg-indicators` for the `scss` updates.
> Accessibility: update footer as unordered list

- _layouts/search.html
Fixes #149 
Minor bugfix, so no docs or tests added.
> Translate 'goal x' on search results page

- _layouts/reportingstatus.html
Fixes #143 
Minor bugfix, so no documentation/tests/etc are included.
> Translate 'indicators' on reporting status page

- _layouts/frontpage.html
Fixes #180 
None
See #180 for description of the problem
* _layouts/frontpage.html
No, this isn't really optional, so doesn't need documentation.
No, this seems not major enough for a test.
> Only add the (fake) goal 18 if there are exactly 17 goals

- _includes/head.html
Merging @SavvasStephanides's changes from https://github.com/open-sdg/open-sdg/pull/231/files into `dac`
> Accessibility: Set Goal page title

- _includes/assets/js/indicatorView.js
> Translate the units of measurement in the Y axis

- _includes/assets/js/search.js
- _includes/search.html
- assets/css/default.scss
For #214 
Can be seen on this [test branch](https://sdg.mango-solutions.com/search-button)
> Change search icon to button

- _includes/assets/js/indicatorModel.js
> Translate each part of the combined disaggregation labels

- _includes/assets/js/plugins/jquery.sdgMap.js
> Translate map regions

- _includes/head.html
This will allow easier CSS selecting for particular layouts.
> Set a body class for each layout

- docs/quick-start.md
> Fix typo in quickstart

- assets/css/default.scss
Created new PR for #259 and #271 as PR #263 had a lot of commits for just one file change.
> Fix search bar styling

- _includes/components/metadata.html
For #294 
https://sdg.mango-solutions.com/markdown-fields/1-2-1/
> Allow markdown in metadata fields

- assets/css/default.scss
This is a proof-of-concept alternative to fixing #305
> Non-fixed disclaimer and no body padding

- docs/configuration.md
- docs/customisation.md
- mkdocs.yml
> Dedicated configuration page in docs

- _layouts/indicator.html
Fixes #204 
Although not sure how to code it with translation (| t) filter. Have tried a couple of different things but haven't had any luck
https://sdg.mango-solutions.com/multiple-sources-1
> get list of sources for graph footer

- _includes/footer.html
Add 'Twitter:'/'Facebook;' before link to social media platform
> Make obvious social media links' platform

- _includes/components/data-notice.html
- _includes/components/indicator-content.html
- _layouts/indicator.html
- assets/css/default.scss
- docs/metadata-format.md
- tests/features/DataNotice.feature
- tests/features/support/mink.js
> Add data notice above catch-all

- _includes/assets/js/indicatorView.js
- _includes/components/charts/chart.html
- _includes/head.html
- _includes/polyfills.html
- _includes/scripts.html
- assets/css/default.scss
Fixes #73 
Can be seen on this [feature branch](https://sdg.mango-solutions.com/html-chart)
> Change chart attributes from canvas to html

- docs/changelog.md
> Changelog updates for 0.8.0

- tests/_config.yml
- tests/features/Map.feature
- tests/features/support/mink.js
This test asserts that very basic map functionality works (the map appears, and the sidebar disappears). Future tests could go further and test whether specific map features work (like the year slider, etc.)
In the commits below you can see a commit ("Change indicator to demonstrate failure") to show what a failure would be like.
> Test for map functionality

- _includes/head.html
Fixes #359
Feature branch: https://sdg.mango-solutions.com/title-fix/1/
> Fix title tag on goal page

- _includes/assets/js/indicatorModel.js
- _includes/scripts.html
- _layouts/indicator.html
- docs/metadata-format.md
Fixes  #329
gives the possibility to create a field for copyright information in the metadata
> Footerfield for Copyright

- _includes/goal-variables.html
- _includes/head.html
- _includes/indicator-variables.html
- _layouts/goal.html
Fixes #369 
I believe the best fix is to set goal variables before the head.
> Set goal variables before head

- _includes/components/edit-buttons.html
- _layouts/indicator.html
- docs/configuration.md
> Configurable URLs for the edit buttons

- docs/changelog.md
This is for tracking the latest changes as we get ready for releasing 0.10.0.
> Changelog updates for 0.10.0

- docs/open-sdg-features.md
- mkdocs.yml
Add page to Read The Docs which showcases features
> Platform features

- _layouts/frontpage.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- _layouts/indicator.html
- _layouts/reportingstatus.html
Fixes #413 
This may not be comprehensive but does fix some problems.
> Escape variables in alt attributes

- docs/architecture.md
- docs/automation/circle-ci.md
- docs/automation/github-actions.md
- docs/automation/github.md
- docs/automation/travis-ci.md
- docs/quick-start.md
- mkdocs.yml
This depends on corresponding changes in open-sdg-site-starter and open-sdg-data-starter:
* https://github.com/open-sdg/open-sdg-data-starter/pull/20
* https://github.com/open-sdg/open-sdg-site-starter/pull/45
> Updating docs to use GitHub Actions

- _includes/footer.html
> Add link to Open SDG to footer

- docs/metadata-format.md
> Warning about long strings of characters and formatting issues

- _layouts/news.html
Fixes #425 
@LucyGwilliamAdmin I haven't tested this - this a quick shot in the dark, in case it works.
> Show post excerpts on news page

- _includes/assets/js/indicatorModel.js
> Ensure that indicator data always has a value

- docs/community.md
Added a line with the Icelandic NRP which launched officially earlier this month.
> Added the Icelandic SDG NRP

- tests/_config.yml
This will be needed to get tests to pass again.
> Remove custom CSS stuff from the test config

- _sass/base/_grid.scss
- _sass/layouts/_footer.scss
- _sass/variables/_colors.scss
- tests/_config.yml
UK feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg_white_bg/
> Set background to white for pages and footer

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/indicatorView.js
Fixes #196 
We've already done a Sass cleanup. A proper javascript refactor would probably involve splitting things into multiple files, but would likely be a bigger job. This is some "low hanging fruit" in that it just removes unnecessary comments and unused variables.
> General javascript cleanup

- _sass/layouts/_indicator.scss
UK site feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/goals_box_shadows/
> Add box shadows to goal tiles.

- _sass/layouts/_header.scss
- _sass/variables/_colors.scss
UK feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg_menu_hover/
> Underline menu items when hovered

- _sass/layouts/_header.scss
UK feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1_titlecasemenu/
> Remove uppercase styling for top menu

- docs/faq.md
- docs/quick-start.md
> Reference the single-repository approach in the quick start

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/indicatorView.js
- _includes/scripts.html
Fixes #443 
This uses the [patternomaly](https://github.com/ashiguruma/patternomaly) library to set a striped background on bars when necessary. I did not do any browser testing.
> Make bars striped when necessary

- _layouts/frontpage.html
- _sass/components/_spacers.scss
- _sass/open-sdg.scss
[UK Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-whitespace/)
Done some basic whitespacing on the homepage for this change. Let me know if it looks good to you or if you'd like to see some changes. Feedback more than welcome.
> Adjust homepage whitespace

- tests/features/Map.feature
This is a minor tweak to help reduce the number of false failures in the automated tests.
> Add some delay before 2 test steps

- docs/open-sdg-features.md
> Document that news/categories pages are not automatically translated

- _includes/assets/js/indicatorView.js
- _includes/polyfills.html
> Update the chart download button when data changes

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/indicatorView.js
- _includes/scripts.html
- _layouts/frontpage.html
- _layouts/indicator.html
- _sass/components/_spacers.scss
- _sass/layouts/_indicator.scss
- _sass/open-sdg.scss
- docs/faq.md
- docs/quick-start.md
[UK feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-tabs/1-2-1/)
> Redesign indicator page tabs

- _includes/assets/js/indicatorView.js
This fixes part of #488 by setting aria-disabled on "Clear selections" button, according to whether or not it is disabled.
> Set aria-disabled on 'Clear selections' button

- _sass/layouts/_header.scss
As per @phillipgardiner's suggestions:
* Increase the width of the search box to 240px
* Increase the font size to 15px
> Change the styling of the search input field

- Makefile
- README.md
Now that we're passing the current accessibility tests, we can make them automatic.
> Make the accessibility tests automatic

- docs/metadata-format.md
- tests/data/_prose.yml
- tests/data/meta/1-1-1.md
- tests/data/meta/1-2-1.md
- tests/data/meta/1-3-1.md
- tests/data/meta/1-4-1.md
- tests/data/meta/1-4-2.md
- tests/data/meta/1-5-1.md
- tests/data/meta/1-5-2.md
- tests/data/meta/1-5-3.md
- tests/data/meta/1-5-4.md
- tests/data/meta/2-2-2.md
- tests/data/meta/2-3-2.md
- tests/data/meta/3-1-1.md
> Documentation of reserved metadata fields

- _layouts/frontpage.html
From `homepage_introduction_banner` to `frontpage_introduction_banner`
> Change frontpage introduction banner config

- docs/reporting-status.md
> More detailed documentation on 'reporting_status_extra_fields'

- docs/metadata-format.md
- tests/data/meta/1-1-1.md
- tests/data/translations/en/tags.yml
- tests/data/translations/es/tags.yml
- tests/data/translations/fr/tags.yml
- tests/features/Tags.feature
> Documentation and tests for the 'tags' metadata field

- mkdocs.yml
@AnnCorp just went to look at case study on read the docs and wasn't showing and then realised it hadn't been added to the list of pages. Sorry!
> Add UK case study

- docs/metadata-file-formats.md
- mkdocs.yml
> Add docs about different formats for metadata input

- _sass/layouts/_search.scss
Fixes #582
Fixes #583
Fixes #584
> Search page tweaks for expert review

- _includes/scripts.html
> jQuery 3.4.1

- _includes/components/metadata.html
> Remove table-hover class and styling

- _sass/base/_mixins.scss
- _sass/layouts/_indicator.scss
This implements changes for:
* #575 
* #570 
* #571
> Indicator cards styling updates

- _sass/layouts/_indicator.scss
@AnnCorp @brockfanning @SavvasStephanides 
Sorry, just realised we haven't added this too project - but think we said we'd put it in to v1?
Before: https://sustainabledevelopment-uk.github.io/3-9-1/
After: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/multi-chart-title-deploy/3-9-1/
> Only show items that can be selected in drop down lists

- docs/quick-start.md
open-sdg-data-starter PR: https://github.com/open-sdg/open-sdg-data-starter/pull/29
> Add instructions for triggering site build

- _sass/components/_high_contrast.scss
> Highlight the high-contrast goal icons on hover

- _includes/assets/js/indicatorView.js
> High-contrast support for y-axis scale label

- _includes/components/dev-disclaimer.html
- _sass/components/_disclaimer.scss
- _sass/components/_high_contrast.scss
- docs/changelog.md
- docs/configuration.md
- docs/updates.md
- tests/data/translations/en/custom.yml
- tests/data/translations/es/custom.yml
- tests/data/translations/fr/custom.yml
- tests/features/Disclaimer.feature
- tests/features/Search.feature
- tests/site/_config.yml
> Disclaimer redesign

- docs/changelog.md
This mentions some includes that were moved as part of #646 
This also fixes some formatting issues.
> Fix changelog format and clarify moved includes

- _layouts/indicator.html
> Move indicator available above indicator content

- _includes/components/indicator/metadata-section.html
> Full-width metadata if indicator is incomplete

- _includes/components/indicator/header.html
- _layouts/frontpage.html
- _layouts/goal-by-target.html
- _sass/base/_typography.scss
- _sass/components/_collapsible.scss
- _sass/components/_maps.scss
- _sass/layouts/_indicator.scss
- _sass/layouts/_reporting_status.scss
- _sass/layouts/_search.scss
- tests/data/meta/3-1-1.md
All these changes are a result of the expert review by @phillipgardiner. 
*The indicator page banner layout change discussed [here](https://github.com/open-sdg/open-sdg/issues/651#issuecomment-622368367) will be done in a different PR*
> Heading styling / font change

- _sass/layouts/_header.scss
> More whitespace around search bar/logo

- _includes/assets/js/model/chartHelpers.js
> Make headline thicker than disaggregation lines

- _includes/assets/js/model/chartHelpers.js
> Fix logic of dataset creation to have null values for missing years

- _sass/components/_high_contrast.scss
> Normal color for high-contrast list items

- docs/faq.md
@AnnCorp was thinking - do we want to include everything from new user page i.e. setting up platform and populating platform?
> Add Q about what resources needed

- _layouts/reportingstatus.html
- tests/data/config_data.yml
Fixes #693 
I believe this was a minor markup issue.
I also turned on extra reporting status fields in the local build, for easier manual testing.
> Reporting status extra fields - markup issue

- _includes/assets/js/plugins/jquery.sdgMap.js
> Download the geojson file instead of opening it

- docs/faq.md
This adds examples for the CSV and GeoJSON download question. And for consistency in formatting, I moved the examples for the API question to their own line.
> FAQ: examples of GeoJSON/CSV paths

- _includes/components/indicator/header.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- _sass/base/_mixins.scss
- _sass/base/_tables.scss
- _sass/base/_typography.scss
- _sass/components/_back_to_top.scss
- _sass/components/_breadcrumbs.scss
- _sass/components/_disclaimer.scss
- _sass/components/_download_buttons.scss
- _sass/components/_goal_banner.scss
- _sass/components/_goal_tiles.scss
- _sass/components/_high_contrast.scss
- _sass/components/_language_toggle.scss
- _sass/components/_maps.scss
- _sass/components/_notices.scss
- _sass/components/_tabs.scss
- _sass/layouts/_footer.scss
- _sass/layouts/_goal.scss
- _sass/layouts/_header.scss
- _sass/layouts/_indicator.scss
- _sass/layouts/_news.scss
- _sass/layouts/_reporting_status.scss
- _sass/layouts/_search.scss
- _sass/open-sdg.scss
- _sass/variables/_colors.scss
This is an attempt to fit a naming convention discussed in #712.
> Update Sass variables to fit a naming convention

- _includes/assets/js/model/chartHelpers.js
Fixes #741 
See this feature branch as test:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/spangaps-test/6-4-2/
> Join data points when data is missing

- _includes/components/indicator/indicator-main.html
> Default to country name for headline label on charts/tables

- _includes/components/indicator/data-panes.html
- _includes/components/indicator/data-tabs.html
- _includes/components/indicator/embedded-feature.html
- docs/metadata-format.md
this is for #383 and #740 - as code it currently it's not possible to add attributes to iframes that are a result of using Pym parent - this means size, title, etc. cannot be set.
> Embed either using either Pym parent or iframe

- _includes/assets/js/indicatorView.js
This is a total shot in the dark and needs real testing, but in theory this fixes #747.
> Correct selector to avoid infinite loop

- _sass/layouts/_header.scss
> Fix styling of mobile menu items

- _includes/assets/js/plugins/jquery.sdgMap.js
> Update tooltips of active selections when the year changes

- _sass/components/_maps.scss
> Hide map selection legend on mobile

- _includes/assets/js/model/chartHelpers.js
> Sort the disaggregations that display in table headers

- _sass/components/_download_buttons.scss
- _sass/variables/_colors.scss
Fixes #748 
I haven't tested this but in theory it should work.
> Visited color for download buttons

- _includes/assets/js/menu.js
- _includes/scripts.html
- _sass/layouts/_header.scss
> Translate mobile search buttons

- _includes/scripts.html
> Alt tag for loading image

- _includes/assets/js/plugins/jquery.sdgMap.js
Thank you @MoBosse for catching this.
> Syntax fix - map tooltips

- _sass/base/_mixins.scss
- _sass/layouts/_reporting_status.scss
- _sass/variables/_colors.scss
- docs/customisation.md
This is intended to fix #770 but needs testing.
> More usage of variables with status colors and borders

- _includes/assets/js/plugins/jquery.sdgMap.js
> Skip map layers that do not have data

- _sass/layouts/_header.scss
> Pad the search bar to avoid hiding terms

- _includes/assets/js/chartjs/noDataMessage.js
- _includes/assets/js/indicatorView.js
- _sass/layouts/_indicator.scss
- assets/js/sdg.js
> Display a no-data message when chart has no data

- _includes/header.html
> Add an anchor for any back-to-top links

- _layouts/news.html
- _layouts/post.html
> H1 in news and post layouts

- docs/metadata-format.md
Just noticed code example not rendering properly. Added extra empty line in between text and code block
> Fix tags code example

- _includes/assets/js/indicatorView.js
- _includes/components/charts/chart.html
- _sass/components/_download_buttons.scss
- _sass/variables/_colors.scss
> Button revamp

- _includes/components/goal/breadcrumbs.html
- _includes/components/post/breadcrumbs.html
- _layouts/goal-by-target-vertical.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- _layouts/indicator.html
- _layouts/post.html
- _sass/components/_breadcrumbs.scss
- _sass/variables/_colors.scss
- _sass/variables/_dimensions.scss
- docs/configuration.md
- tests/site/_config.yml
> New breadcrumb configuration and separator

- docs/maps.md
> Add config example for data repository map settings

- _includes/head.html
- tests/features/Accessibility.feature
- tests/features/Search.feature
- tests/site/Gemfile
- tests/site/_config.yml
> Page titles

- _includes/assets/js/accessibility.js
- _includes/components/indicator/data-panes.html
- _includes/components/indicator/metadata-panes-default.html
- _includes/components/indicator/metadata-panes.html
- _layouts/reportingstatus.html
> Better keyboard accessibility for tabbed content

- _layouts/reportingstatus.html
- _sass/layouts/_reporting_status.scss
> More space beneath reporting status goal items

- _includes/assets/js/accessibility.js
- _includes/components/indicator/data-panes.html
- _includes/components/indicator/metadata-panes-default.html
- _includes/components/indicator/metadata-panes.html
- _layouts/reportingstatus.html
> Revert "Better keyboard accessibility for tabbed content"

- _includes/components/charts/chart.html
> H4 instead of H3 for chart title

- _includes/assets/js/menu.js
- _includes/header.html
- _sass/layouts/_header.scss
> Use buttons for the mobile menu/search drop-downs

- _includes/assets/js/indicatorView.js
- _includes/components/indicator/data-sidebar.html
- _sass/components/_download_buttons.scss
- _sass/layouts/_indicator.scss
Fixes #867 
Discussion in #867
> Accessibility improvements for chart legends

- _includes/components/dev-disclaimer.html
> Remove alert role from disclaimer

- _sass/base/_typography.scss
- _sass/layouts/_header.scss
- _sass/layouts/_search.scss
- _sass/variables/_colors.scss
> Use darker text color and default to white text in high-contrast

- _includes/assets/js/indicatorView.js
- _sass/base/_links.scss
Fixes #850 (partially)
Still under discussion at #850.
> Default mouse cursor on disabled elements

- _includes/components/indicator/fields-template.html
- _includes/components/indicator/series-template.html
- _includes/components/indicator/units-template.html
- _sass/layouts/_indicator.scss
Fixes #842 
Note that for the screenreader-only text, I tried to re-use existing language so that we would not need to do any new translations. So the text is not exactly as recommended by DAC in #842.
I did a quick test locally and did not see any visual problems or functionality issues.
> Fieldsets around radios and checkboxes

- _includes/components/post-categories.html
> Use aside instead of div for news sidebar

- docs/configuration.md
> Update docs for recent plugin changes

- _includes/assets/js/indicatorView.js
- _includes/components/indicator/fields-template.html
- _sass/layouts/_indicator.scss
> aria-described-by for indicator disaggregation variable hint

- _sass/layouts/_indicator.scss
> Make sure pressed legend items get line-through

- _includes/components/charts/chart.html
> Alert role and screenreader-only warning label for too-many-datasets

- _includes/head.html
- _includes/title-tag.html
- tests/features/Accessibility.feature
Demonstration of adding site title to page title.
> Add site title to page title

- _includes/assets/js/indicatorView.js
> Only announce no data, added data, or removed data.

- _includes/components/indicator/header.html
- _layouts/goal-by-target-vertical.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- _layouts/reportingstatus.html
- _sass/components/_goal_tiles.scss
For #870 
feature branch with svgs: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/svgs
feature branch with pngs: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/background-images
> Add background colour to goal icons

- _includes/components/indicator/fields-template.html
- _sass/layouts/_indicator.scss
Fixes #930
Fixes #928
This also includes a fix for #928 because it affects the same code.
This will need translation afterwards.
> More descriptive disaggregation button label/hierarchy for screenreaders

- _includes/assets/js/tabs.js
> Make the active tab panel focusable

- _includes/assets/js/indicatorView.js
- _includes/components/indicator/fields-template.html
> aria-describedby for no-data-hint

- _includes/assets/js/indicatorView.js
> Remove role from datatable

- _includes/assets/js/indicatorView.js
- _sass/components/_download_buttons.scss
- _sass/layouts/_indicator.scss
This is a proof of concept to show what is involved in removing the legend clickability. It affects quite a bit of code and required some style tweaks.
> Remove legend clickability

- _includes/assets/js/plugins/leaflet.yearSlider.js
- _sass/components/_maps.scss
Fixes #940 
Fixes #939 
Fixes part of #937 (the part about the map slider)
> Map slider accessibility

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/model/fieldHelpers.js
> Consider hierarchy when sorting fields

- _includes/assets/js/indicatorView.js
Fixes the latest comment mentioned in #921
> Remove rowspan and colspan from table headers

- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/plugins/leaflet.fullscreenAccessible.js
- _sass/components/_maps.scss
- assets/js/sdg.js
Fixes the parts of #936 and #937 that have to do with the fullscreen button.
> Map fullscreen accessibility

- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/plugins/leaflet.searchAccessible.js
- _sass/components/_maps.scss
- assets/js/sdg.js
Fixes #938 
Fixes the parts of #937 related to the search button
Fixes the parts of #936 related to the search button
> Map search accessibility

- _includes/assets/js/chartjs/accessibleCharts.js
- _includes/assets/js/indicatorView.js
- _includes/components/charts/canvas.html
- _includes/components/charts/chart.html
- _includes/components/indicator/data-footer.html
Fixes #961 and some other things that have been strongly advised by DAC:
- screen reader text for legend
- screen reader text for footer
> Chart accessibility additions

- _includes/assets/js/tabs.js
> Always focusable tab panes

- _includes/assets/js/indicatorView.js
> Remove aria-label from table headers

- _includes/assets/js/chartjs/accessibleCharts.js
- _includes/components/charts/canvas.html
This also normalizes some text to make it easier to translate later.
> Different canvas fallback for mobile/desktop.

- _includes/scripts.html
An extra curly brace snuck into our code...
> Remove extra brace from annotations script call

- _includes/scripts-custom.html
- _includes/scripts.html
- docs/configuration.md
- docs/customisation.md
- tests/features/CustomJavascript.feature
- tests/site/_config.yml
- tests/site/custom.js
> Better support for third-party and remote javascript files.

- _includes/footer.html
- docs/configuration.md
> Allow translated href in footer menu links

- docs/metadata-file-formats.md
@brockfanning was just looking at docs and realised that it's tags and not tag
> Correct metadata field name

- .github/workflows/codeql-analysis.yml
Just want to see the output of the codeql workflow
> Codeql test

- _layouts/page.html
- tests/data/custom-translations/en/custom.yml
- tests/data/custom-translations/es/custom.yml
- tests/features/Page.feature
- tests/site/_pages/about-en.md
- tests/site/_pages/about-es.md
> Translate page titles and content

- docs/automation/triggered-site-builds.md
- docs/quick-start.md
- docs/translation.md
- docs/troubleshooting.md
- docs/tutorials/add-indicator.md
- docs/tutorials/add-language.md
- docs/tutorials/change-banner.md
- docs/tutorials/change-colors.md
- docs/tutorials/change-logo.md
- docs/tutorials/frontpage-config.md
- docs/tutorials/override-markup.md
- mkdocs.yml
> Quickstart section revamp with tutorials

- docs/configuration.md
> Mention that remote_data_prefix can actually be a local folder

- _includes/components/indicator/table.html
> Remove stray character in table markup

- _sass/layouts/_goals.scss
- _sass/layouts/_reporting_status.scss
> Margin below descriptions on reporting-status and goals pages

- _sass/layouts/_goal-by-target-vertical.scss
> Increase goal-by-target-vertical indentation

- tests/features/Search.feature
Fixes #590 
Since this PR is only automated tests, no manual testing is needed. As long as the automated tests pass (which they do) then it should be OK to merge.
> Multlingual search tests

- _includes/components/download-all-data.html
- tests/data/requirements.txt
- tests/site/Gemfile
This depends on a PR in sdg-build: https://github.com/open-sdg/sdg-build/pull/189
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/configurable-indicator-download-filename/
> Use configured zip filename

- docs/automation/github.md
@brockfanning this line is no longer true now that quick start has been cut down to minimum so think we should delete it
> Remove about not needing to do this

- docs/tutorials/add-language.md
This section wasn't rendering as code so added some extra empty lines around it
> Fix code section

- _includes/assets/js/chartjs/accessibleCharts.js
- _sass/components/_download_buttons.scss
#710 
Testing instructions: Let's make sure that the image download still looks good in both normal and high contrast, with and without selected disaggregations.
> High-contrast chart image downloads

- _includes/components/post/post-listing.html
- _layouts/news.html
- _sass/base/_typography.scss
- _sass/layouts/_news.scss
- _sass/variables/_typography.scss
Fixes #1057 
EDIT: [Feature Branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/news-style-updates)
> Updates to news layout markup/style

- pull_request_template.md
Currently looks like this (updated following feedback):
Q | A
--- | ---
Fixed issues | #`issue`
Bugfix, feature or docs |
Updated docs/config-forms? |❌/✔️
So filled in for this PR as an example (updated following feedback):
Q | A
--- | ---
Feature branch/test site URL | NA
Fixed issues | #1077
Related version | master
Bugfix, feature or docs | Feature
Most of these fields came from this [example on json-editor repo](https://github.com/json-editor/json-editor/pull/882) but I've added some others.
Let me know if you think there's any we should remove or if …
> Create template for PRs

- _includes/components/indicator/tags.html
- _layouts/goal-by-target-vertical.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- _sass/base/_mixins.scss
- _sass/components/_tags.scss
- _sass/layouts/_goal-by-target-vertical.scss
- _sass/layouts/_goal-by-target.scss
- _sass/layouts/_goal.scss
- _sass/open-sdg.scss
- _sass/variables/_colors.scss
Fixes #373 
Note that this does not affect the tags on the News page, but I think a follow-up ticket to make them consistent would be good. However that should not be started until this PR and #1078 have both been merged.
EDIT: [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/tag-style-updates)
> Refactor and style updates for tags on goal pages

- _layouts/config-builder.html
In the config forms, after filtering the list of settings, it is impossible to get back to the full list. This adds a reset button for this purpose.
> Reset button for config forms

- _includes/assets/js/chartjs/rescaler.js
- _includes/assets/js/indicatorView.js
- _includes/assets/js/model/dataHelpers.js
- _includes/assets/js/model/seriesHelpers.js
- _includes/assets/js/model/unitHelpers.js
- _includes/components/charts/graph_limits.html
- _includes/components/indicator/fields-template.html
- _includes/scripts.html
Fixes #943 
To test this, we should mainly focus on indicator pages, and making sure that everything still works.
EDIT: [Feature Branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/underscore-to-lodash/)
> Switch to Lodash instead of Underscrore

- _includes/components/indicator/sources.html
- tests/data/meta/1-1-1.md
This is an attempt to address one issue mentioned in #504
> Add gutter to sources tab

- _sass/layouts/_indicator.scss
Q | A
--- | ---
Fixed issues | Fixes #1106
> Fix contrast of too-many-datasets message

- _sass/layouts/_indicator.scss
Q | A
--- | ---
Fixed issues | Fixes #1115 
> Yellow hover color for disaggregation values in dropdown

- _includes/assets/js/accessibility.js
Q | A
--- | ---
Fixed issues | Fixes #1118
Updated docs/config-forms? | NA
Added CHANGELOG entry? | NA (because this fixes a bug in the same release)
> More precise image switching code

- _includes/assets/js/indicatorView.js
- _includes/assets/js/model/constants.js
- _includes/components/charts/line.html
Fixes #1094 
EDIT: [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/more-contrast-chart-grid-lines-1)
> Color adjustments for chart grids

- .github/workflows/test-pull-requests.yml
Another version of #1135 to go into 1.3.0-dev.
> Pin to Ubuntu 18.04 because 20.04 doesn't work for tests

- _sass/base/_typography.scss
Q | A
--- | ---
Fixed issues | Fixes #1124 and #1134
JW Edit: [Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/footer-text-focused-high-contrast)
> Fix text color in focused high-contrast div

- _includes/assets/js/indicatorController.js
- _includes/assets/js/indicatorView.js
- _includes/assets/js/plugins/jquery.sdgMap.js
This is a few scattered backwards compatibility additions to avoid errors that may happen when users upgrade to 1.3.0 while a changed file has been overridden.
Q | A
--- | ---
Feature branch/test site URL | NA
Includes tests? | NA
Updated docs? | NA
> 1.3.0 backwards compatibility fixes

- _includes/assets/js/chartColors.js
- _includes/assets/js/indicatorView.js
- docs/configuration.md
I accidentally merged #1145 into 1.4.0-dev, but we need this for 1.3.0-dev.
> Chart color tweaks 1 3 0 correct branch

- docs/translation.md
> New language update

- docs/changelog.md
- docs/configuration.md
- docs/updates.md
- docs/upgrades/upgrading-1-3-0.md
- mkdocs.yml
> Changelog updates for 1.3.0

- _includes/components/reportingstatus/reporting-status-label.html
- _layouts/goal-by-target-vertical.html
- _layouts/goal-by-target.html
- _layouts/goal.html
Q | A
--- | ---
Feature branch/test site URL | [EFT-Defra/open-sdg#EFT-Defra-patch-1](https://github.com/EFT-Defra/open-sdg/tree/1.4.0-dev)
Fixed issues | n/a
Bugfix, feature or docs? | n/a
Keeps backward-compatibility? | Not tested
Updated docs? |❌
Updated config forms? |❌
This is a very minor syntactic change motivated by my attempts to familiarise myself with Jekyll and OpenSDG. More than anything, it's intended to show willing, so feel free to reject!
> replace series of IFs with CASE

- _includes/components/goal/header.html
- _layouts/goal-by-target-vertical.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- docs/changelog.md
Q | A
--- | ---
Includes tests? |NA (existing tests cover this)
This removes some duplicate code and also makes it easier to customize the goal header.
> Move goal header to include file

- docs/release-checklist.md
Fixes #1151 
This is meant to be a template that we can copy/paste into Github issues for each new release, to help make sure we remember to do all the steps. I've tried this out already in #1152
> Checklist for new releases

- _sass/variables/_colors.scss
- docs/changelog.md
Q | A
--- | ---
Fixed issues | Fixes #1058 
Added CHANGELOG entry? |✔️
This darkens the main nav text color and also the underline on hover.
> Darker color for main nav

- _sass/layouts/_footer.scss
Q | A
--- | ---
Fixed issues | Fixes #1052 
> Left-align wrapped menu items in footer

- _includes/components/header/logo.html
- docs/configuration.md
- docs/jekyll-templates.md
- tests/features/Logo.feature
- tests/features/support/mink.js
- tests/site/Gemfile
- tests/site/_data/site_config.yml
Q | A
--- | ---
Fixed issues | Fixes #1031 
Includes tests? |✔️
Updated config forms? |✔️
Depends on https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/86
EDIT:
Instructions for testing:
- Create feature branch with 2 languages
- Point feature branch at logo-per-language for open-sdg **and** jekyll-open-sdg-plugins (in Gemfile)
- Follow instructions in doc file in Files changed tab
> Logo per language

- _includes/assets/js/indicatorView.js
Q | A
--- | ---
Fixed issues | Fixes #1155 
Related version | 1.3.0
Includes tests? |na
Updated docs? |na
Updated config forms? |na
Added CHANGELOG entry? |na
This is a regression bug, so should be released as a hotfix (1.3.1), so this PR would be merged into master.
> Fix label of tooltips

- tests/features/Data.feature
> Trying to fix a failing test

- docs/configuration.md
- docs/tutorials/create-pages.md
- mkdocs.yml
Q | A
--- | ---
Feature branch/test site URL | NA
Bugfix, feature or docs? | docs
> Tutorial for creating pages

- docs/metadata-format.md
Q | A
--- | ---
Feature branch/test site URL | NA
Related version | NA
> Add example for configuring series-unit combo settings

- _includes/assets/js/model/fieldHelpers.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/hierarchy-sorting-fix-3)
Fixed issues | Not reported - see below
This is a work in progress - and may eventually be closed. I am not able to recreate an actual need for this, but I wanted to document this as a potentially being needed. If any problems arise with the disaggregation control sorting, this may be related.
> Another disaggregation control hierarchy sorting fix

- _sass/base/_mixins.scss
- _sass/components/_download_buttons.scss
- _sass/layouts/_header.scss
- _sass/variables/_colors.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators)
Fixed issues | Fixes #1114 
Keeps backward-compatibility? |✔️ (technically a change but minor)
> High-contrast consistency for buttons

- _sass/layouts/_news.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/updates/)
Fixed issues | Fixes #1160 
> Extra margin under news listings

- _includes/assets/js/backToTop.js
- _includes/back-to-top.html
- _sass/components/_back_to_top.scss
- assets/js/sdg.js
- docs/jekyll-templates.md
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/publications/) (with component) and [Link](https://lucygwilliamadmin.github.io/sdg-indicators/faq/) (with #top link) - see bottom of pages
Fixed issues | Fixes #1055 
Keeps backward-compatibility? |✔️ (technically a change but minor)
> Back-to-top component and styling

- _includes/head-custom.html
- _includes/head.html
- docs/changelog.md
- docs/jekyll-templates.md
Q | A
--- | ---
Keeps backward-compatibility? | ✔️
Added CHANGELOG entry? | ✔️ 
This makes it easier for implementations to have custom stuff in their `<head>`. An example would be using a web font.
> Custom head include

- _includes/assets/js/indicatorView.js
- _includes/assets/js/model/chartHelpers.js
- _sass/layouts/_indicator.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/)
Fixed issues | Fixes #1102 
Keeps backward-compatibility? |✔️ (technically a change, but an improvement)
Includes tests? | NA
Updated docs? | NA
Updated config forms? | NA
> Square points for headline on line charts

- docs/data-configuration.md
Our data configuration documentation is fairly out-of-date, so this refresh is needed before 1.4.0 is released.
> Data config documentation updates

- _includes/assets/js/search.js
- _layouts/search.html
- tests/features/Search.feature
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/search/?q=)
Fixed issues | Fixes #1192
Includes tests? |✔️
This depends on the latest translations.
> Handle searches with no input

- _sass/layouts/_goal-by-target-vertical.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/1/)
Fixed issues | Fixes #1195 
Includes tests? | NA
Updated docs? | NA
Updated config forms? | NA
Screenshot to refer to:
> Max width so that status will wrap on goal-by-target-vertical

- tests/features/LanguageSwitcher.feature
This tweaks an automated test to work with the latest translations.
> Update a test to work with the 2020 updates

- docs/community.md
> Add some users

- tests/data/requirements.txt
- tests/site/Gemfile
Doing this as part of the 1.4.0 release checklist.
> Point to new dev branches in tests

- _includes/components/charts/graph_limits.html
Q | A
--- | ---
Fixed issues | Fixes #1182 
> Graph limits fix

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/model/helpers.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-series-test/15-1-2/)
Fixed issues | Fixes #1266 
Keeps backward-compatibility? | ✔️
> Add missing method (getSeriesFromStartValues) and ensure valid starting unit

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/model/helpers.js
Need to merge this change into 1.4.0-dev
> Missing method get series for start values 2

- _includes/assets/js/model/fieldHelpers.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-disagg-freeze-fix)
Fixed issues | Fixes #1267
Added CHANGELOG entry? |NA (optimization only needed because of another change in this release)
> Another attempt to optimize getCombinationData

- docs/indicator-configuration.md
> Fix typo in graph_limits section

- pull_request_template.md
Q | A
--- | ---
Fixed issues | Fixes #1077 
> Updating PR template

- docs/quick-start.md
> Embed quick start video tutorial

- _includes/assets/js/plugins/jquery.sdgMap.js
- docs/changelog.md
Q | A
--- | ---
Fixed issues | Fixes #1248 
> Remove invalid values from map ranges

- _layouts/goal-by-target-vertical.html
- _layouts/goal-by-target.html
- _layouts/goal.html
- _sass/layouts/_goal-by-target-vertical.scss
- _sass/layouts/_goal.scss
- docs/changelog.md
- docs/indicator-configuration.md
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-placeholder-indicators/11/)
Fixed issues | Fixes #1275 
This PR is supported by two other PRs:
* https://github.com/open-sdg/sdg-build/pull/275
* https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/108
> Placeholder indicators

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/model/chartHelpers.js
- _includes/components/charts/annotation_presets.js
- _includes/components/charts/graph_annotations.html
- _includes/components/charts/line.html
- _includes/components/indicator/indicator-main.html
- _includes/scripts.html
- docs/changelog.md
- docs/indicator-configuration.md
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-annotations-test) (see 1.1.1)
Fixed issues | Fixes #1297 
This PR is supported by a [PR on jekyll-open-sdg-plugins](https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/107) and a [PR on sdg-translations](https://github.com/open-sdg/sdg-translations/pull/229).
> Updates to annotation defaults and simpler versions for target_lines and series_breaks

- tests/data/requirements.txt
- tests/site/Gemfile
Administrative PR - no testing needed.
> Update branches for 1.6.0-dev

- _sass/base/_typography.scss
> Don't recolour links in notices

- docs/changelog.md
- docs/updates.md
- docs/upgrades/upgrading-1-5-0.md
This is not intended to be reviewed/merged yet, but is here to provide upgrade instructions as we release beta versions.
> 1.5.0-beta1 upgrade instructions

- pull_request_template.md
> Update 'Related version'

- docs/indicator-configuration.md
> Examples for graph_target_lines & graph_series_break

- docs/data-configuration.md
> Added IDRIS (Metadata Report Config)

- docs/hosting/github-pages-production.md
> Revert "Update github-pages-production.md"

- docs/automation/github.md
> Embed video tutorial for automation docs

- _includes/assets/js/model/helpers.js
- _includes/components/indicator/fields-template.html
- docs/changelog.md
- docs/updates.md
- docs/upgrades/upgrading-1-6-0.md
- mkdocs.yml
Release notes for 1.6.0. To be updated as we work through the beta testing.
> Release notes for 1.6.0-beta

- docs/data-configuration.md
Q | A
--- | ---
Related version | N/A
> Sdmx output docs

- docs/tutorials/frontpage-config.md
> Update to mention site_config.yml

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/model/dataHelpers.js
- _includes/assets/js/model/helpers.js
- docs/changelog.md
- docs/configuration.md
- tests/data/data/indicator_2-2-2.csv
- tests/features/Disaggregation.feature
- tests/site/_data/site_config.yml
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-ignore-disaggregation-columns)
Fixed issues | Fixes #1434 
Bugfix, feature or docs? | feature
This needs careful testing, in case there is some unintended consequence.
> Ignore disaggregation columns

- tests/data/indicator-config/1-1-1.yml
- tests/data/indicator-config/1-2-1.yml
- tests/features/EmbeddedFeature.feature
- tests/features/support/mink.js
- tests/site/_pages/iframe.html
Q | A
--- | ---
Fixed issues | Fixes #645 
Bugfix, feature or docs? | Tests only
> Tests for embedded features

- _includes/assets/js/indicatorView.js
- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/components/indicator/data-panes.html
- _includes/components/indicator/data-tabs.html
- docs/changelog.md
- docs/configuration.md
- docs/indicator-configuration.md
- tests/site/Gemfile
- tests/site/_data/site_config.yml
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-indicator-tab-order)
Fixed issues | Fixes #1435 
Bugfix, feature or docs? | feature
This depends on https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/121
The failing test is because the tests are not pointed at that branch.
> Indicator tab order

- _includes/components/charts/graph_limits.html
Q | A
--- | ---
Fixed issues | Fixes #1483 
> Remove graph limits if there should be none

- _includes/assets/js/model/fieldHelpers.js
Q | A
--- | ---
Fixed issues | Fixes #1477 
> Handle case where starting value does not exist in selected series

- docs/automation/triggered-site-builds.md
Q | A
--- | ---
Fixed issues | Fixes #1393
> Embed youtube video

- _includes/assets/js/indicatorView.js
- _includes/components/indicator/data-footer.html
- docs/indicator-configuration.md
- tests/data/indicator-config/2-5-2.yml
- tests/features/Indicator.feature
- tests/features/support/mink.js
Q | A
--- | ---
Feature branch/test site URL | [[Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-footer-fields)]
Fixed issues | Fixes #1395 
> Support for footer_fields indicator configuration

- tests/data/requirements.txt
> Switch to https protocol in Python requirements

- docs/data-configuration.md
> Fix link to SDMX metadata input class

- _includes/assets/js/plugins/jquery.sdgMap.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-chartjs-3-map-fix/3-a-1/)
Fixed issues | Fixes #1562 
Related version | 1.8.0-dev
> Fix selector for map preparation

- _includes/components/indicator/data-notice.html
- _sass/base/_typography.scss
- _sass/components/_notices.scss
- _sass/layouts/_indicator.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-notice-style-updates/archived-indicators/1-a-1-archived/)
Fixed issues | Fixes #1545 
Related version | 1.8.0-dev
> Styles updates for data notices

- _includes/assets/js/indicatorView-legacy.js
- _includes/assets/js/indicatorView.js
- _includes/assets/js/view/helpers.js
- _includes/assets/js/view/unitHelpers.js
- _includes/components/indicator/data-footer.html
- _sass/layouts/_indicator.scss
- tests/features/Indicator.feature
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-dynamic-unit-in-data-footer/15-2-1/)
Fixed issues | Fixes #1549 
Related version | 1.8.0-dev
> Dynamic unit of measurement in data footer

- _includes/footer-custom.html
- _includes/footer.html
Example to show a possible approach for #1544 
Feature branch: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-footer-custom-include/
> Include file for custom footer content

- _includes/bootstrap5/components/post/breadcrumbs.html
- _layouts/post.html
Quick fix for breadcrumbs on posts in bootstrap_5 mode.
> Fix breadcrumb markup in bootstrap 5 posts

- docs/configuration.md
- docs/maps.md
Q | A
--- | ---
Fixed issues | Fixes #1213 
> Expand a bit more on map documentation

- _sass/base/_typography.scss
Q | A
--- | ---
Fixed issues | Fixes #1632
> Explicitly turn off text indent

- _sass/base/_menus.scss
- _sass/components/_contrast_toggle.scss
- _sass/variables/_typography.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-main-nav-font-size/)
Fixed issues | Fixes #1619 
> Larger font size for main nav

- _sass/base/_locale.scss
- _sass/open-sdg.scss
This file was deleted unintentionally in a recent 2.0.0 deprecations PR.
> Recover locale scss file

- _includes/assets/js/backToTop.js
- _layouts/goal.html
- _layouts/indicator.html
- _layouts/initiative.html
- _layouts/initiatives.html
- _layouts/reportingstatus.html
- _sass/components/_back_to_top.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-back-to-top-on-some-pages/)
Fixed issues | Fixes #1622 
> Back-to-top cleanup and added to goals/indicators/status pages

- _layouts/config-builder.html
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-config-form-js-error/1-1-1/config/)
Fixed issues | Fixes #1658 
> Pin to 2.6.1 of json-editor

- _layouts/data-editor.html
- _sass/layouts/_data_editor.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-form-button-placement/1-1-1/data/)
Fixed issues | Fixes #1659 
> Style fixes for data edit form

- _includes/components/page/breadcrumbs.html
- _layouts/categories.html
- _layouts/goals.html
- _layouts/initiative.html
- _layouts/initiatives.html
- _layouts/news.html
- _layouts/page.html
- _layouts/reportingstatus.html
- _layouts/search.html
- _layouts/standalone-indicators.html
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-page-breadcrumbs/)
Fixed issues | Fixes #1625 
> Breadcrumbs on all pages

- docs/indicator-configuration.md
> Document some options for styling tags

- _sass/components/_maps.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-high-contrast-fixes/3-3-3/)
> High-contrast fixes for map

- _includes/components/header/internet-explorer-message.html
- _includes/head.html
- _includes/header.html
- _sass/components/_header.scss
- assets/css/ie.css
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-ie-message)
This relies on translations from an "ie-message" sdg-translations branch. So the data config also needs to be updated to test this:
```
translations:
- class: TranslationInputSdgTranslations
source: https://github.com/brockfanning/sdg-translations.git
tag: ie-message
```
> IE message

- _includes/assets/js/view/chartHelpers.js
Q | A
--- | ---
Fixed issues | Fixes #1712 
> Fix for rescaler plugin when changing series

- Makefile
- docs/indicator-configuration.md
- docs/tutorials/add-indicator.md
- tests/site/Gemfile
Sarah recently completed this step for her platform setup and flagged the create indicator guidance as a point of confusion at which she got stuck so have added an extra step in the guidance to check which branch you are on.
> Docs updates July 2022

- docs/analytics.md
- docs/hosting/production.md
These documentation fixes are meant to correct the production and analytics guidance according to the latest version.
> Documentation fixes related to analytics and production config

- docs/reporting-status.md
These are updates to the reporting status documentation to match the latest config structure.
> Updates to the reporting status documentation

- _includes/assets/js/plugins/leaflet.disaggregationControls.js
Q | A
--- | ---
Feature branch/test site URL | [Link](https://dnsupgradeenvironment.github.io/dns-indicators/)
Fixed issues | Fixes #1788 
> Translations in leafletDisaggregationControls

- _includes/scripts.html
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-lodash-upgrade)
Fixed issues | Fixes #1770 and #1769
> Lodash and jQuery upgrades

- _sass/layouts/_goal.scss
Q | A
--- | ---
Fixed issues | Fixes #1745 
> Horizontal rule thickness fix on goal pages

- _includes/components/indicator/metadata.html
> Support local hrefs in metadata links

- _includes/assets/js/plugins/leaflet.yearSlider.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-remove-map-play-button/3-3-3/)
Fixed issues | Fixes #1807 
> Remove play button from maps

- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/view/chartTypeBase.js
- _includes/assets/js/view/dataHelpers.js
- docs/configuration.md
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-chart-tooltip-use-raw/16-1-1/)
Fixed issues | Fixes #1796 
> Use raw value for chart tooltip

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/model/dataHelpers.js
- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/plugins/leaflet.selectionLegend.js
- _includes/javascript-variables.html
- docs/customisation.md
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-indicator-id-in-data-rounding/16-1-1/)
Fixed issues | Fixes #1822 
> Pass a second parameter to dataRounding which includes indicator id

- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/plugins/leaflet.yearSlider.js
- _sass/components/_maps.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-slider-start-fix/)
Fixed issues | Fixes #1815 
> Make sure the year slider appears to be on the correct year

- docs/hosting/github-pages-production.md
> Clarify custom domain and remote_data_prefix

- _includes/assets/js/plugins/leaflet.disaggregationControls.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disagg-function-fix)
Fixed issues | Fixes #1836 and #1838 
> Map disaggregation: name the function and the flag differently

- _includes/assets/js/plugins/leaflet.searchAccessible.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-fuzzy-fix/3-3-3/)
> Use more fuzzy searching for maps

- _sass/layouts/_config_builder.scss
- _sass/layouts/_data_editor.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-config-form-high-contrast-fixes/config/)
Fixed issues | Fixes #1701 
> Contrast fixes for data/config forms

- _includes/assets/js/search.js
- _layouts/search.html
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-search-suggestion-stem-fix/)
Fixed issues | Fixes #1846
This is intended to fix the issues in #1846. This needs testing of the search functionality, by running searches to do (and do not) have any results.
> Search suggestion stem fix

- _sass/components/_maps.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disaggregation-max-width/3-3-3/)
Fixed issues | Fixes #1847 
> Max width for map disaggregation on desktop

- _includes/assets/js/plugins/leaflet.searchAccessible.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-search-role-removal/3-3-3/)
Fixed issues | Fixes #1849 
> Map search role removal

- _includes/components/reportingstatus/reporting-status-label.html
- tests/site/_data/site_config.yml
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-no-data-available-tag/1/)
> Use reporting status label in site configuration

- .github/workflows/test-pull-requests.yml
- _includes/assets/js/view/chartHelpers.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-chart/3-1-1/)
Fixed issues | Fixes #1894 
> Double-size chart image downloads

- docs/automation/travis-ci.md
- docs/glossary.md
- docs/making-updates.md
- docs/support.md
- docs/tutorials/frontpage-config.md
- mkdocs.yml
> Feature docs revamp

- docs/robots.txt
> Adding a Robots.txt file

- docs/customisation.md
- docs/open-sdg-features.md
> Latest changes made by Otis

- _includes/assets/js/indicatorModel.js
- _includes/assets/js/indicatorView.js
- _includes/assets/js/mapView.js
- _includes/assets/js/plugins/jquery.sdgMap.js
- _includes/assets/js/plugins/leaflet.disaggregationControls.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-data-start-values-for-maps/3-3-4/)
Fixed issues | Fixes #1889 
> Use data_start_values for maps

- docs/changelog.md
- docs/updates.md
- docs/upgrades/upgrading-2-2-0.md
Upgrade instructions: https://github.com/brockfanning/open-sdg/blob/2.2.0-release/docs/upgrades/upgrading-2-2-0.md
> Docs updates for 2.2.0 release

- docs/configuration.md
- docs/indicator-configuration.md
@sarah-beasley @Govej I forget to add these docs before. Can you give feedback on these instructions? https://github.com/open-sdg/open-sdg/blob/cecb5ee46dc179729a80fd787ce6219c0bd1ab06/docs/configuration.md#create_goals
> Docs for goal_headings

- docs/indicator-configuration.md
Just updating as i think it should say 'both' there, rather than 'proxy'? Please let me know if this is wrong though!
> Updating proxy guidance

- .github/workflows/test-pull-requests.yml
- _includes/components/indicator/indicator-main.html
- tests/features/Indicator.feature
Q | A
--- | ---
Fixed issues | Fixes #2014 
> Translate country name in table header

- _includes/assets/js/view/chartHelpers.js
- _includes/assets/js/view/tableHelpers.js
- _includes/assets/js/view/utils.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-unit-and-series-in-chart-download/1-4-1/)
Fixed issues | Fixes #2022 
> Add series and unit to chart/table CSV downloads

- _layouts/search.html
- _sass/layouts/_search.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-search-result-sem/search/?q=poverty)
Fixed issues | Fixes #2030 
> Semantic markup for search result breadcrumbs

- _includes/components/indicator/sources-alt.html
- _includes/components/indicator/sources.html
Q | A
--- | ---
Fixed issues | Fixes #2032 
> Additional context for screenreaders when only 1 source

- _includes/assets/js/plugins/leaflet.disaggregationControls.js
Testing instructions to be discussed.
Q | A
--- | ---
Fixed issues | Fixes #2062 
> Only use valid start values for maps

- _includes/assets/js/indicatorView.js
- _includes/assets/js/view/chartHelpers.js
- _includes/assets/js/view/helpers.js
- _includes/components/indicator/indicator-main.html
Q | A
--- | ---
Fixed issues | Fixes #2053 
> Screenreader statuses for switching unit and series

- _includes/assets/js/indicatorModel.js
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-series-change-starting-values/3-b-1/)
Fixed issues | Fixes #2071
> Do not use starting values when changing series

- _sass/components/_data_table.scss
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-scrollable-table-high-contrast/1-2-1/)
Fixed issues | Fixes
> High contrast fixes for scrolled tables

- docs/data-configuration.md
- docs/data-sources.md
> Sdmx .stat guidance

- docs/configuration.md
Can check images in the preview of the file - https://github.com/open-sdg/open-sdg/blob/04a859246ae6b9f8fbc5b958564739f0fc9785e1/docs/configuration.md
> Adding site config images

- docs/configuration.md
- docs/indicator-configuration.md
- docs/tutorials/change-logo.md
If you could just check these bits added to the logo guidance and progress reporting make sense, that would be great!
> Feature update logo and reporting progress guidance

- _layouts/data-editor.html
This fixes a problem where an empty data file is missing the Value column in the data edit form. (for example: https://open-sdg.org/open-sdg-site-starter/1-2-1/data/)
> Upgrade ag-grid and fix missing value column

- docs/configuration.md
- docs/indicator-configuration.md
- docs/maps.md
- docs/upgrades/upgrading-2-2-0.md
- docs/upgrades/upgrading-2-3-0.md
> adding indicator config images

- _layouts/data-editor.html
Q | A
--- | ---
Fixed issues | Fixes #2157 
Related version | 2.4.0-dev
> Do not export rows in data edit form with empty values

- _includes/head.html
- _includes/scripts.html
- _layouts/data-editor.html
- _layouts/search.html
- docs/architecture.md
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-sri-hashes-test/)
Fixed issues | Fixes #2139 
Related version | 2.4.0-dev
> Add SRI hashes to script tags

- _includes/assets/js/config-schema/schema-indicator-config.json
- _includes/assets/js/config-schema/schema-site-config.json
- tests/site/_data/site_config.yml
Testing instructions: Let's make sure that the config forms (both site and indicator) still work as expected with this change.
Recommend this in the site repo's Gemfile:
`gem 'jekyll-open-sdg-plugins', git: 'https://github.com/open-sdg/jekyll-open-sdg-plugins.git', branch: '2.4.0-dev'`
> JSONSchema type fixes.

- _includes/assets/js/config-schema/schema-site-config-ui.json
- _includes/assets/js/config-schema/schema-site-config.json
- _layouts/config-builder.html
- docs/configuration.md
Q | A
--- | ---
Related version | 2.4.0-dev
> Allow configurable js library for config forms

- docs/progress.md
- mkdocs.yml
Add info about progress calculation components output file to progress documentation page. Add progress documentation page to sidebar.
> Progress status documentation update

- _includes/components/indicator/indicator-content.html
Q | A
--- | ---
Related version | 2.5.0-dev
> If page content already has html, do not markdownify it.

- docs/progress.md
> Indentation Fix
