_includes/header.html

This is a breaking change, so existing implementations will need to update their menu config. Instead of just having "reporting_status" (like before), it will need to say "menu.reporting_status".

Allow any translation file for menu items - fixes #8

---

_includes/assets/js/accessibility.js

This avoids the accumulation of slashes in the image paths when toggling back and forth from high-contrast mode.
Fixes #35

Avoid extra slashes in image paths

---

docs/quick-start.md

Going through the quick-start again, it seems that this PEM change actually does cause a problem with Github. So I think we need to revert it. More investigation may be needed into when/where it is needed.

Change key-gen command back to simpler version

---

_includes/head.html
_includes/indicator-variables.html
_layouts/default.html
_layouts/frontpage.html
_layouts/goal.html
_layouts/indicator.html
_layouts/initiative.html
_layouts/initiatives.html
_layouts/reportingstatus.html
_layouts/search.html

- This removes some unused variables from indicators.html
- Multilingual.html is not directly included in the head. It must be
added to the top of any layout now.
- Indicator variables move about the head.html include to fix #64
- layouts adjusted to directly include multilingual.
Replacing #65

move indicator and multilingual variables to own files #64

---

_includes/components/metadata.html
_layouts/goal.html
assets/css/default.scss
docs/metadata-format.md

This adds support for an optional `tags` metadata field on indicators. The assumption here is that the `tags` field is an array of strings. The most common use-cases would probably be tags like "National" or "Local" to highlight the fact that certain indicators have been customised for a country or city.
Out of the box, the tags appear beneath the indicators on the goal pages, with yellow backgrounds. You can see a demo [here](http://brock.tips/sdg-site-maptest/no-poverty/). However the tags get unique HTML classes that would allow an implementation to customise the style (eg, the background color) per tag.
Also, the HTML element wrapping the whole indicator gets a unique class per tag, allowing custom styling of indicators having a certain tag. For example, a city implementation might …

Support for tagging indicators on goal pages

---

tests/_config.yml

This tweak is necessary for working tests, now that open-sdg-site-starter has switched to using some Ruby Gems for Jekyll plugins.

Load Ruby Gem plugins for tests and configure data correctly

---

_includes/assets/js/plugins/jquery.sdgMap.js

This tweaks the hack that gets around a weird interaction between zoomShowHide and zoomSearch.
Also this updates the default max_zoom for layers to 10, as 20 is a ridiculously high zoom.
Fixes #103

Improve hack for incompatibility betwen zoomShowHide and zoomSearch

---

_includes/header.html
tests/features/Navigation.feature

This uses a new "t" Liquid filter provided by the jekyll-open-sdg-plugins Ruby Gem to translate the menu item labels, instead of the rather confusing Liquid code that's doing it now.
**This is a breaking change!** It requires sites to be loading the jekyll-open-sdg-plugins Ruby Gem.

Switch to using the new 't' filter for menu item labels.

---

_layouts/goal.html

This allows for translated indicator tags. It relies on a Liquid filter "t" which is provided by the jekyll-open-sdg-plugins Ruby Gem. But the way Jekyll treats missing filters is to just fail gracefully, so if the filter is not there then nothing will change. So, this is not a breaking change.
Fixes #93

Run tag labels through the t filter

---

_layouts/frontpage.html
_layouts/indicator.html

Also, include the country adjective IN the frontpage header, rather than putting them side by side.
This depends on https://github.com/open-sdg/sdg-translations/pull/56 so it should not be merged until that issue has been merged.
The "t" filter referenced here is provided by the jekyll-open-sdg-plugins Gem. If a site is missing that plugin, the "t" filter will do nothing (fail gracefully).
Fixes #62

Run country name/adjective through the "t" filter.

---

_includes/components/metadata.html

This change adds a new way to have multilingual metadata. First I'll describe the existing way:
The `meta` folder in the data repository can have subfolders for each language, and corresponding .md files can be put there to extend/override an indicator's metadata for that particular language. This is a fairly straightforward way to do it, and is great for translating one-off bits of text, like descriptions, keywords, etc.
The case where that is **not** great is for translating common words/phrases. If every single indicator needs "Office of Statistics" translated, it is a bit duplicative to have to copy/paste the translations of "Office of Statistics" for every single indicator.
Now I'll describe what this PR adds:
This PR offers a new option which works better in that use-case. Instead …

Translate the output of metadata fields

---

_layouts/goal-by-target.html
assets/css/default.scss
docs/customisation.md

This adds an optional goal layout for displaying targets in the left column and indicators in the right column.
Fixes #54

Add an optional layout for a grouped-by-target goal page

---

_includes/assets/js/search.js

This use decodeURIComponent instead of unescape. Apparently this handles non-latin characters better, as it fixes search for Armenian/Russian.
Fixes #115

Better character handling in search code

---

_layouts/indicator.html

There are a few graph-related metadata fields that could go through the "t" filter, for extra flexibility in translation.

Translate several graph-related metadata fields

---

_layouts/indicator.html

This will allow implementations to easily control the text of the non-global metadata tab. It includes a default of the translated text "National Metadata". Because of the default this is not a breaking change.
If this is merged then I'll add the `non_global_metadata` option to [this file](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml), which is currently serving as our documentation of `_config.yml` options.
Fixes #52

Allow configuration of tab for non-global metadata

---

_includes/assets/js/indicatorView.js
assets/css/default.scss

Fixes #106 
One note though: I feel like we should be using the jquery.dataTables library to generate table markup, instead of looping through the data to generate it with custom code. My first thought in implementing this was to use the jquery.dataTables options "columnDefs", "cellType", and "createdCell". This should have worked, but we're generating our table markup outside of jquery.dataTables. Not a pressing issue, but in the future it might be nice if we could trim our custom code and leverage jquery.dataTables more. All that said, there may well be a good reason for the way it is now, that I don't know about.

Set scope=row on cells in the Year column

---

_includes/assets/js/googleAnalytics.js
_includes/footer.html
assets/js/sdg.js

This PR moves the google analytics code into a separate file `googleAnalytics.js` which can then be overridden without having to override the whole page footer.
I did sneak in another change, which I want to check with you @brockfanning. Rather than disabling `ga` for staging I've put it so that it checks for a `ga_prod` string in the config. If it has one, it'll use `ga`, if not, it won't. This is set from the line:
```
{% if site.analytics.ga_prod %}
initialiseGoogleAnalytics();
{% endif %}
```
This makes no changes for the UK. How about the US and other countries?
See #125

Refactor Google Analytics code

---

_includes/indicator-variables.html
_layouts/frontpage.html
_layouts/reportingstatus.html
tests/features/Goal.feature
tests/features/Multilingual.feature

In #84 we discussed switching to numbers for goal paths. This PR makes this change.
Obviously this is a major breaking change, but the switch-over is not difficult to make. It just involves updating the 17 files in the `_goals` folder. For each file in the `_goals` folder, should replace the line:
```
permalink: /no-poverty/
```
to...
```
permalink: /1/
```
..and so on, for each of the 17 goal pages.
I also tested out the [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) plugin, and it works great! Here are the basic instructions for that:
1. Add `gem "jekyll-redirect-from"` to the Gemfile
2. Add `- jekyll-redirect-from` in the list of `plugins` in `_config.yml`
3. Update each of the 17 goal files with a `redirect_from` field, like so:
```
redirect_from:
- …
```

Change to numbers for goal paths

---

Makefile
_includes/assets/js/indicatorView.js
_includes/components/fields-template.html
_includes/components/headline.html
_includes/components/units-template.html
_includes/head.html
_includes/multilingual-js-base.html
_layouts/indicator.html
docs/translation.md
tests/data/translations/en/data.yml
tests/data/translations/es/data.yml
tests/features/Disaggregation.feature
tests/features/support/mink.js

This allows for the translation of the disaggregation data columns/values, including the filters on the left, the columns of the data tables, the CSV exports, and the chart legends.
For indicators this depends on the translation keys being in a "data" translation group. I've started an [issue](https://github.com/open-sdg/sdg-translations/issues/70) in the SDG Translations project to do some translating of common disaggregation-related words.
This has a breaking change in the `head.html` include. If any implementer has overridden head.html then they will need to update it.
Also included are relevant documentation updates and Cucumber tests.
Fixes #5

Translate disaggregation filters/columns

---

_includes/assets/js/indicatorModel.js
_includes/indicator-variables.html
_layouts/frontpage.html
_layouts/reportingstatus.html
tests/features/Goal.feature
tests/features/Multilingual.feature

Update to `indicatorModel.js` to ignore Observation status and Unit multiplier fields when displaying the data in the site.
I haven't been able to test if it actually works because `jekyll serve` is giving me weird errors. Please let me know if you can run it.

Ignore Observation status and Unit multiplier fields

---

_includes/assets/js/plugins/jquery.sdgMap.js

There is functionality, particularly in the year slider, that assumes the years array is sorted from first to last. But in practice it isn't necessarily sorted that way, so let's ensure that.

Sort the years array in maps, to fix first/last year functionality

---

_layouts/goal-by-target.html
_layouts/goal.html
_layouts/search.html
assets/css/default.scss
docs/metadata-format.md

* Everywhere we reference `notstarted` etc I add `notapplicable`
* goal-by-target.html gets an update on the css to use status rather than danger, warning, success.
Fixes #130

add notapplicable as fully supported status #130

---

_includes/assets/js/indicatorView.js

Fixes #142 
This change treats the chart's "source" footer item in the same was as the "footnote" item, to let it wrap lines.
This is a quick alternative to the much more involved #179. A benefit of this approach is that the metadata still makes it into the downloaded image of the canvas.

Graph source text wrap

---

_includes/assets/js/plugins/jquery.sdgMap.js

Fixes #178 
This makes sure that the variable in question is always an array of responses, even when there is only one. So it will behave the same whether there is one layer or multiple.

Allow either multiple or single map layers

---

_includes/indicator-variables.html
_layouts/goal-by-target.html
_layouts/goal.html
_layouts/indicator-json.html
_layouts/indicator.html
tests/_config.yml
tests/data/translations/en/metadata.yml
tests/data/translations/es/metadata.yml
tests/features/LanguageSwitcher.feature
tests/features/MultilingualMetadata.feature

This refactors a few places where indicator names are needed. Mostly it changes the code from relying on global indicator names, to using a new filter in jekyll-open-sdg-plugins that figures out the indicator name in a more forgiving way.
The upside of this change is that if countries are using national/proxy/etc indicators, the custom indicator name will appear instead of the current behavior, which is that the name is either global or missing altogether.
This requires that the Gemfile for a site be updated to pull in at least version 0.0.10 of the jekyll-open-sdg-plugins Gem, like [this](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/Gemfile#L8).
Otherwise there are a lot of changed files, but it won't break anything if they are overridden. One unnecessary variable has …

More robust way to display indicator names

---

_includes/footer.html
tests/_config.yml
tests/features/Footer.feature

Fixes #151 
None.
After merging, the [open-sdg-site-starter config file](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml) should have this added to it under the `twitter` line:
```
#facebook: MyFacebookAccount
```
* _includes/footer.html
We don't have documentation of individual _config.yml settings (though we probably should). For now the [open-sdg-site-starter config file](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml) serves as the documentation for all of these settings.
Yes.

Add facebook option to footer

---

_includes/assets/js/accessibility.js
_includes/assets/js/autotrack-element.js
_includes/assets/js/googleAnalytics.js
_includes/assets/js/indicatorView.js
_includes/autotrack.html
_includes/scripts.html
_layouts/indicator.html
assets/js/sdg.js
docs/analytics.md
mkdocs.yml
tests/data/autotrack.yml
tests/features/Analytics.feature

Fixes #125 
* If `assets/js/sdg.js` is being overridden, this update will cause javascript errors. To resolve, either remove the `assets/js/sdg.js` file from your site repository, or incorporate the latest changes to that file.
This uses Google's autotrack.js library, and some Jekyll includes, to allow for out-of-the-box event tracking, plus optional overriding of the category/action/label of the events. It includes some brief documentation.
This "wires up" the following events:
* User changes data tabs (Table, Chart, etc.)
* User changes metadata tabs (National, Global, etc.)
* User changes the contrast setting
* User downloads a CSV file
This hopefully captures everything decided on in #125 
* _includes/assets/js/accessibility.js
* _includes/assets/js/googleAnalytics.js
* …

Autotrack for Google Analytics

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js
_includes/scripts.html
_layouts/indicator.html
docs/data-format.md
tests/features/Headline.feature

Fixes #174 
None.
Right now, when there is no headline, the first field is automatically selected. For many cases this is fine, but it doesn't work in cases where more than 1 field is needed to display data.
An example of such as place is: https://onsdigital.github.io/sdg-indicators/10-6-1/
* _includes/assets/js/indicatorModel.js
* _includes/assets/js/indicatorView.js
* _includes/scripts.html
* _layouts/indicator.html
Yes.
Yes.

Better selection of fields when there is no headline

---

_includes/components/charts/binary.html

Fixes #176 
None
See #176 for a description of the problem.
* _includes/components/charts/binary.html
No, this is a bug fix.
No because it would be too difficult, as far as I know, to test the output of canvas elements.

Ensure binary graphs always stretch from Yes (1) to No (-1)

---

_layouts/frontpage.html
assets/css/default.scss
tests/_config.yml
tests/data/translations/en/custom.yml
tests/data/translations/es/custom.yml
tests/features/Homepage.feature
tests/features/LanguageSwitcher.feature

Fixes #146 
None.
See #146 for details of the problem.
After merging, the [open-sdg-site-starter config file](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml) should have this added to it:
```
#frontpage_heading: This is my frontpage heading
#frontpage_instructions: These are my frontpage instructions
```
* _layouts/frontpage.html
* assets/css/default.scss
* believe at one point, probably before the open-sdg revamp, the jump-to-search was truly a "progressive enhancement", in that the whole phrase was hidden until javascript revealed it. At the moment it's only part of the phrase that's hidden, and the markup is tied up in sdg-translations, so is difficult to change. So I'm not worrying too much here about progressive enhancement. Long-term I think we should …

Configurable frontpage headings

---

_includes/components/fields-template.html

Moved `aria-expanded='false'` label from `<div>` to `<button>` to fix an issue with the screen reader not announcing the expanded/collapsed status

[Accessibility] Disaggregation accordions: Move ARIA expanded status to button

---

_includes/assets/js/chartjs/rescaler.js
_includes/assets/js/indicatorView.js
tests/features/Analytics.feature
tests/features/Headline.feature

Fixes #175 
This allows "0" to appear in both charts and tables. Previously there were some "truthy" checks that were unintentionally filtering out zeroes. This change looks specifically for "null" instead, which lets the zeroes get through.
Minor enough bug fix, no docs or tests needed.

Support zero values

---

_includes/multilingual-js-base.html
docs/translation.md
tests/data/translations/en/data.yml
tests/data/translations/es/data.yml

If any countries were relying on a behind-the-scenes lower-case conversion of disaggregations before being translated, those disaggregations would no longer get translated. No countries are actually doing this, and it fails gracefully and obviously, so I would not call this a "breaking change".
Right now there is a convenience check, when displaying disaggregation labels, which looks in a translation group called "data" for a lower-case version of the whatever the label is. Documentation exists [here](https://open-sdg.readthedocs.io/en/latest/translation/#translating-data-disaggregations-and-columns).
The problem is the lower-case part. A common use-case is for a country to copy/paste _exactly_ what is in their data (CSV files) into the data.yml as the translation keys. But the lower-case …

A more precise check for data (disaggregation) translations.

---

_includes/indicator-variables.html
_layouts/goal-by-target.html

None (backwards-compatibility is included)
However note that after adopting the translation updates in [this PR](https://github.com/open-sdg/sdg-translations/pull/93) a country would need to update their version of jekyll-open-sdg-plugins to 0.0.12, [like so](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/Gemfile#L8).
This is to support a potential change in SDG Translations, from dot-delimited translation keys to dash-delimited translation keys. See [here](https://github.com/open-sdg/sdg-translations/issues/92) for details.
The main use-case for this change is to allow countries to add translation keys for global indicators in their metadata. For example, they can put the following in an indicator's metadata file:
```
graph_title: global_indicators.1-1-1.title
``` …

Expect dash-delimited translation keys for indicators/targets

---

_includes/assets/js/menu.js
assets/css/default.scss

The current default interface on the mobile top level menu (Menu, Search) is a series of `<span>` elements. To improve accessibility for screen readers, the `menu.js` script, which deals with expanding and collapsing the menu and search bar on mobile, needs to support replacing `<span>` elements to `<button>`s. 
This pull request is done in conjunction with a request on SDG UK's `sdg-indicators` where the `span`s are replaced with `button`s to improve accessibility. [Test branch here](https://sdg.mango-solutions.com/a11y-mobile-menu-to-button/).

Accessibility: Enable support for buttons on mobile top level menu

---

_includes/assets/js/indicatorModel.js
_includes/javascript-variables.html
_includes/scripts.html

This change removes the data rounding function, which has been causing issues recently. It also adds an easier way for countries to add custom rounding, without needing to override any files. Finally it adds a way to add custom javascript, through the site config, similar to the `custom_css` config option.
Fixes #199

Remove data rounding and provide an easier way to add custom rounding

---

_includes/assets/js/indicatorModel.js
_includes/multilingual-js-base.html

We recently added code to allow zeroes in data to survive into the charts/tables, but we forgot this one spot: the headline data.

Catch another spot where zeroes are getting clobbered: the headline

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js
_includes/components/units-template.html

Correct the initially-selected unit when headline doesn't use first unit

---

assets/css/default.scss

Make sure the target name is also white in high-contrast

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js

This makes the treatment of the footer fields more consistent between the table and chart, by having both use the same object. It also takes care of a TODO.
Fixes #238

Refactor/cleanup of footerFields for charts/tables

---

_includes/components/fields-template.html

Fixes #245 
This problem can be observed [here](https://armstat.github.io/sdg-site-armenia/am/1-2-1/). See how the English "Sex" appears in the midst of the disaggregation widget's help text. This PR should fix it so that word is translated as well.

Translate the var_hint_replacement variable

---

_includes/header.html

Page.url is more reliable, since it is a Jekyll-generated variable that doesn't depend on user configuration.
This also increases consistency in the logic by removing slashes before comparing the current path to the menu item path. This avoid confusing "misses" when a trailing slash is used or not used in the menu config.

Use page.url instead of page.permalink to determine active menu item

---

_layouts/indicator.html

Saves having to add JS to metadata files. Can be used like this:
`embedded_content_url: https://www.ons.gov.uk/visualisations/dvc529/multiline/index.html`
`embedded_content_title: A nice title`

Clean up embed + allow for configurable title

---

_includes/assets/js/indicatorView.js

Ensure that the state of the expandable and collapsible content is identified. For example, the elements should be read as expandable or collapsible. Provide ariaexpanded="false" and change the value of the aria-expanded attribute as per the action.

Move aria-expanded to button

---

_includes/assets/js/indicatorView.js

Screen reader users would expect check boxes to announce ‘Checkbox checked’ and ‘Checkbox not checked’ respectively.

Indicate when check boxes have been selected

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js

This should fix #262 
This updates the automatic "minimum field" selection logic, for when an indicator has no headline. It should also look for a unit, and "force" this unit if necessary.

Force a specific unit if needed when there is no headline

---

_includes/assets/js/indicatorView.js

Ensure that the state of the expandable and collapsible content is identified. For example, the elements should be read as expandable or collapsible. Provide ariaexpanded="false" and change the value of the aria-expanded attribute as per the action.

Screen reader to read if dropdown is expanded/collapsed

---

_includes/assets/js/menu.js
_includes/header.html

When the screen readers is focused on the Menu link on mobile, the reader reads it as "Menu toggle. Click to expand or collapse the menu".
The link now has aria-expanded and aria-haspopup attributes that help the reader know this is an expandable menu
When the user clicks on the Menu, the focus switches automatically to the first element in the menu ("Goals"). This will make it easier to navigate the menu from a screen reader.

Fix mobile menu

---

open-sdg.gemspec

This is a preemptive PR for the next minor release, 0.8.0. With jekyll-open-sdg-plugins version 0.0.13, the jekyll-get-json plugin is no longer required. So this updates the gemspec file accordingly.
Breaking change: After this change, all sites will need to have jekyll-open-sdg-plugins 0.0.13 or later. So this should also be accompanied by a corresponding change in open-sdg-site-starter.

Require jekyll-open-sdg-plugins 0.0.13, and not jekyll-get-json

---

_includes/assets/js/accessibility.js
_includes/header.html
assets/css/default.scss
docs/configuration.md

Using the line `contrast_type: long` in their config file, countries can choose whether to use the small 'A' contrast buttons or the longer 'Default contrast'/'High contrast' button
Here's a feature branch where `contrast _type: long`:
https://sdg.mango-solutions.com/optional-contrast/

Add optional contrast button

---

_includes/head.html

This avoids a console message in Firefox: "The page was reloaded, because the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. The encoding declaration needs to be moved to be within the first 1024 bytes of the file." Probably not a big deal, but an easy fix.

Move charset up to beginning of head

---

_includes/components/breadcrumb.html
_includes/indicator-variables.html
_layouts/frontpage.html
_layouts/goal-by-target.html
_layouts/goal.html
_layouts/indicator-json.html
_layouts/indicator.html
_layouts/reportingstatus.html
tests/_config.yml

The sdg-translations project now has "flattened" global translation keys. For example, instead of this:
```
1:
title: Foo
2:
title: Bar
```
...now has this:
```
1-title: Foo
2-title: Bar
```
As a consequence several parts of the templates in Open SDG need to be adjusted. This is an attempt at that, as well as a general cleanup/deprecation of some indicator variables.

Support flattened global translations

---

_includes/components/charts/bar.html
_includes/components/charts/line.html
docs/metadata-format.md
tests/features/SetMinMaxValues.feature

For #348 
This PR will allow data providers/editors to set a min and max value on the y-axis using new metadata fields `graph_min_value` and `graph_max_value`
Test branch:
https://sdg.mango-solutions.com/set-axis-test
Bar chart test:
https://sdg.mango-solutions.com/set-axis-test/5-5-1/
Line graph test:
https://sdg.mango-solutions.com/set-axis-test/16-6-2

Allow min and max value be set on y axis

---

docs/changelog.md

Readthedocs.io is a little more strict about Markdown than I'm used to, and requires a space before the beginning of a bulleted list.

Fix markdown syntax in docs

---

_layouts/indicator.html
docs/metadata-format.md

Added a section below the embed within the embed tab where info about the embedded feature can go e.g. source, footnote.
[Here](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/5-4-1-embed-deploy/5-4-1/)'s an example of how it would look.
Also I realise to be in line with #394 `meta` should be `page.indicator` but wasn't sure which PR that should be part of?

Add footer to embed tab

---

assets/css/default.scss

Currently some placeholder text is cut off if language is anything but English - change to using `width: auto` so no text is cut off in any language

Auto fit search bar around text

---

tests/_config.yml

Because jekyll-open-sdg-plugins should now be setting the default language on all goals, indicators, and pages, this confusing snippet can be removed from the _config.yml files. Let's confirm by removing it in the test suite.

Remove the default language snippet, since it is no longer needed

---

_includes/footer.html
_includes/header.html
docs/configuration.md
tests/_config.yml
tests/features/Footer.feature

This is an attempt at #412.
The upside of this approach is that we don't need specific configuration settings for Twitter and Facebook. So along those lines, those configuration items are removed from the documentation. This also makes it easier to add additional footer menu items.
There is a downside - or at least a change of behavior: The Twitter and Facebook links can't include the account names. For example, instead of "Twitter: @MyTwitterAccout" it has to be just "Twitter". This is because the labels of the menu items have to be controlled by a single "translation key".
Finally this also includes a fix for the main menu as well. Apparently there is a problem with the main menu when the site does not have a "baseurl" - this would only have been visible on a production site, so maybe …

Configurable footer menu links

---

_layouts/indicator.html
docs/metadata-format.md
tests/features/Indicator.feature
tests/features/support/mink.js

Fixes #337 
This changes the H2 on the indicator pages to `indicator_available` instead of `graph_title`.
This could be considered a breaking change. The most probable result for most implementations will be that the H2 will disappear, since there is nothing in the `indicator_available` field. On the bright side, this isn't so bad, because that H2 was just duplicating the graph title anyway.

Use indicator_available instead of graph_title for the indicator page H2

---

docs/quick-start.md

After releasing 1.0.0-rc1 of sdg-build, I've updated the open-sdg-data-starter repo to utilize the new "config file" approach. Accordingly I'm updating these quick start directions.

Tweaks to the quick start based on recent changes in starter repos

---

_includes/components/metadata.html
docs/metadata-format.md

Fixes #171 
This utilizes a filter from the latest version of jekyll-open-sdg-plugins (1.0.0-rc13), and clarifies in the documentation how to rename metadata fields.

Metadata field translation keys

---

_includes/header.html
_sass/layouts/_header.scss

This change moves the search box above the top menu navigation in the header
UK feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg_move_search/

Move search box above the top navigation

---

_sass/layouts/_header.scss

This change keeps the searchbox the same size when in focus
UK feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/static_search/

Keep searchbox the same size when in focus

---

Makefile
_includes/components/post-categories.html
_layouts/categories.html
_layouts/news.html
_layouts/post.html
_sass/base/_mixins.scss
_sass/layouts/_news.scss
docs/configuration.md
docs/open-sdg-features.md
tests/_config.yml
tests/data/translations/en/custom.yml
tests/data/translations/es/custom.yml
tests/data/translations/fr/custom.yml
tests/features/News.feature
tests/posts/2020-01-10-test-post1-en.md
tests/posts/2020-01-10-test-post1-es.md
tests/posts/2020-01-10-test-post1-fr.md

Fixes #433 
This updates the news-related layouts to work with multilingual sites, including translated dates. It adds automated tests for news functionality and documentation about the feature.
Visually one change included is that the post categories are styled like indicator tags. Also, the post categories have been moved to the bottom of the post (beneath the content) instead of the top (above the content).

Multilingual news/posts

---

_sass/base/_typography.scss
_sass/components/_goal_tiles.scss

This change implements the following changes on the top banner:
* Set the background color to white
* Change the text on the banner to black
* Change the link text to dark grey (`#ddd`)
* Add some whitespace on the banner to give more prominence
[UK feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-topbanner/1/)

Change the styling of the top banner on goal and indicator pages

---

docs/upgrading.md
mkdocs.yml

I believe we have a gap in our documentation in regards to performing upgrades, so this is a first draft to fix that. This is only general documentation. I think we should make a separate document specifically about upgrading to version 1.0.0.

Documentation on upgrading dependencies

---

_includes/search.html

This fixes something that pa11y (see #484) is complaining about on all pages. I basically moved the aria-label from the icon to the button element. Hopefully this still satisfies the UK accessibility standards. Would love your feedback @SavvasStephanides.

Set aria-label on search button

---

_includes/assets/js/search.js
_includes/javascript-variables.html
_layouts/search.html

Fixes #480 
This works for languages covered by lunr-languages. See here for a list: https://github.com/MihaiValentin/lunr-languages/
This also provides a fallback search functionality for any other languages.

Use lunr-languages plugin, or simple fallback search, for non-english languages

---

_includes/components/headline.html

We have a data table that is rendered in HTML, but hidden with javascript. However, it wasn't compatible with the "translated builds" approach, where the data repo has separate builds for each language. This fixes that.
Side benefit: this fixes the pa11y complaint about layout tables mentioned in #488

Look for translated builds when rendering the no-javascript headline

---

_sass/layouts/_indicator.scss

This fixes part of #488 by giving the tabs black text, for more contrast.
@SavvasStephanides @phillipgardiner

Black text for tab links

---

_layouts/indicator.html
_sass/base/_typography.scss

Removes the goal line from indicator page and changes the indicator title to `<h1>`
**Note**: I tried to align the title vertically, but haven't been able to in a way that would fit both short and long titles. Let's leave it at that at the moment and revisit later.

Remove goal line from indicator banner

---

_layouts/frontpage.html
_sass/layouts/_homeintro.scss
_sass/open-sdg.scss

This change adds an introductory paragraph to the frontpage, right above the goal tiles.
The banner text is retrieved by translations, so the text for both the title and description must be added to `frontpage.yml` in order for the banner to show up (which also makes it optional).
Example `frontpage.yml`:
```yml
intro_title: 17 Goals to transform our world
intro_description: The Sustainable Development Goals are a call for action by all countries – poor, rich and middle-income – to promote prosperity while protecting the planet. They recognize that ending poverty must go hand-in-hand with strategies that build economic growth and address a range of social needs including education, health, social protection, and job opportunities, while tackling climate change and environmental …
```

Add an introduction banner to the frontpage

---

_includes/scripts.html

This resolves an issue with the edge case of a site using local data (instead of remote data) and untranslated builds. The problem was the the javascript variable `remoteDataBaseUrl` was just `/`, and this was getting concatenated with `/comb/etc...` to make: `//comb/etc...`. Browsers were interpreting that as `https://comb/etc...` was was causing those requests to fail.

Fix for the edge case of local data with untranslated builds

---

_includes/components/download-all-data.html
_layouts/frontpage.html
_sass/components/_download_buttons.scss
tests/data/config_data.yml
tests/features/Homepage.feature

Fixes #380 
This depends on:
* The latest version of jekyll-open-sdg-plugins: 1.0.0.rc22
* The latest translations from [open-sdg/translations-open-sdg](https://github.com/open-sdg/translations-open-sdg)
The file size and last updated date come from the sdg-build library.
English:
French:
Full page:

Bulk download link beneath the homepage grid

---

.gitignore
Makefile
docs/about.md
docs/configuration.md
docs/customisation.md
docs/data-sources.md
docs/development.md
docs/faq.md
docs/making-updates.md
docs/metadata-format.md
docs/open-sdg-features.md
docs/quick-start.md
docs/reporting-status.md
docs/translation.md
docs/upgrading.md

This changes a lot of links in the documentation to relative instead of absolute. It also adds to the Makefile some commands for serving/testing the documentation.
A follow-up ticket could easily make the documentation tests part of the normal PR tests.

Documentation link fixes and testing

---

Makefile
tests/features/Goal.feature
tests/features/HighContrast.feature
tests/features/Homepage.feature
tests/features/ReportingStatus.feature
tests/features/Search.feature

The purpose of this is only to speed up the automated testing process. A side-benefit is that it also speeds up the "make serve" local development tool. The downside is that only Goals 1-3 are available on the test site, but I don't think that's necessarily a problem. This PR adjusts all the automated tests so that they work with the smaller set of indicators.
I'll see how long this PR takes to test, and edit this comment to report on how much faster it actually is.
EDIT:
* For automated PR tests, this reduces the time from 7 minutes to 5 (saves 2 minutes)
* For local development, this reduces the 'make serve' from 115 seconds to 40 seconds (saves 75 seconds)

Test only the minimum amount of data/metadata

---

_includes/assets/js/chartColors.js
_includes/assets/js/indicatorModel.js
assets/js/sdg.js

This should allow to define a set of colors in the site-repositories config-file to be used in the charts.
Fixes #326

allow the use of user-defined colors

---

_sass/components/_high_contrast.scss
tests/features/Homepage.feature
tests/site/_config.yml

This sets the introduction banner text to white while in high contrast, fixing the bad contrast issue
Before:
After:

Make the introduction banner work in high contrast

---

_includes/assets/js/accessibility.js
_includes/assets/js/indicatorView.js
_includes/polyfills.html
_sass/layouts/_indicator.scss

Fixes #579 
This sets the following colors:
Normal contrast:
* Grid lines: `#ddd`
* Axis labels: `#000`
High contrast:
* Grid lines: `#222`
* Axis labels: `#fff`
Let me know if I should tweak those colors.
Side notes:
1. This fixes a problem where we were setting the swatch for headlines to white, but it needs to stay grey.
2. This fixes a problem where the swatch hover color was bad in high-contrast mode
3. There are a few random white-space/indentation fixes in accessibility.js.
4. There is still an issue with the headline color, which right now is hardcoded to 777777 (see [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorModel.js#L192)). Really that should be white/black depending on the contrast mode, probably. But at least it appears to be meeting …

High-contrast fixes for chart grids/ticks

---

_sass/components/_disclaimer.scss
_sass/components/_download_buttons.scss
_sass/layouts/_footer.scss
_sass/layouts/_header.scss
_sass/layouts/_indicator.scss

Fixes #567 
Fixes #568
To fix the items above and preempt other left-alignment concerns, this is intended to make several elements flush to the left margin, at all breakpoints:
1. The "alpha" disclaimer
2. The main logo
3. The homepage goal grid
4. The main menu (it goes to the left at a particular screen width)
5. The footer menu
Note that on mobile, the background for the disclaimer and main menu need to extend all the way to the edge of the screen.

Various fixes to make more elements flush to the left

---

_includes/assets/js/plugins/jquery.sdgMap.js

This makes sure the map_layers warning actually appears, and also makes it more specific.

Fix error message for missing map_layers

---

_includes/components/units-template.html
_layouts/indicator.html
_sass/layouts/_indicator.scss

Fixes #601 
This is a simple change, but I also changed the "Units type" header from an H5 to an H4, because otherwise it would be smaller than "Sub-categories" (which is an H4). Here's a screenshot:

Move units above subcategories and promote to H4 instead of H5

---

_includes/components/indicator-content.html

This is to support the translation of the indicator content (in the metadata files, the stuff below the `---`).
This would allow something like this:
```
my_field: my value
my_other_field: my other value
---
indicator_descriptions.1-1-1
```
Then if there was a translation file called "indicator_descriptions.yml" containing an item for "1-1-1", then that translation would get used for the indicator content.
This is a quick fix to help with the fact that the "subfolder" approach to translation was removed recently. We should follow up with:
1. Tests and documentation for this functionality
2. Revisiting whether the subfolder approach could be supported

Allow translation of indicator content

---

Makefile
docs/about.md
docs/architecture.md
docs/automation/travis-ci.md
docs/configuration.md
docs/customisation.md
docs/data-sources.md
docs/development.md
docs/faq.md
docs/glossary.md
docs/hosting/aws-s3.md
docs/hosting/github-pages.md
docs/hosting/linux-server.md
docs/index.md
docs/making-updates.md
docs/metadata-file-formats.md
docs/metadata-format.md
docs/open-sdg-features.md
docs/quick-start.md
docs/reporting-status.md
docs/social-media-sharing.md
docs/translation.md
docs/upgrading.md
mkdocs.yml

Fixes #599 
Fixes #612 
I've probably added too much for one PR, but here is what is in this PR:
1. Update all "here" links in the documentation to make them more descriptive
2. Update all internal links in the documentation to follow this simpler format: `[my link](my-page.md)` (instead of, for example, `[my link](https://open-sdg.readthedocs.io/en/latest/my-page/)`.
3. Add more documentation of how to fork sdg-translations
4. Fix a few broken links in the documentation, and turn on automated "HTML proofing" for the documentation, to ensure that we never add a broken link to the documentation pages

Documentation link audit and translation docs

---

_sass/base/_mixins.scss
_sass/layouts/_indicator.scss

This change implements the recommendations by @phillipgardiner:

[Expert review] Goal page styling updates

---

_sass/components/_high_contrast.scss

In case you want to see different sizes, here's an animation starting at 16px (the current size) and going  down to 15px, 14px, 13px, and 12px:

Font size 14px for long contrast switcher

---

docs/configuration.md

This PR includes:
1. Make the configuration settings listed in alphabetical order
2. Instead of separate sections for optional/required, indicate optional/required at the beginning of descriptions.

Make the configuration documentation alphabetical

---

_sass/layouts/_header.scss

This pull request moves the colo(u)red banner from the bottom of the header to the very top of the page
Desktop:
Mobile:

Move colored bar to top of page

---

_includes/assets/js/model/chartHelpers.js
_includes/assets/js/model/constants.js

Since the indicatorModel.js refactor, bar charts with headlines are displaying white bars instead of the correct color. In doing the indicatorModel.js refactor I misinterpreted what the background color was for - it turns out that it's for the color of the bars.

Fix color for bar charts with headlines

---

docs/metadata-file-formats.md

Slight tweak because the asterisk was confusing the Markdown parser, I think.

Clarification of tags without using asterisk

---

docs/automation/circle-ci.md
docs/deployment.md
docs/requirements.md

Some references to CircleCI need to be updated, since we've switched the starter repos to Github Actions.

CircleCI updates in docs

---

_sass/base/_mixins.scss
_sass/base/_tables.scss
_sass/base/_typography.scss
_sass/components/_breadcrumbs.scss
_sass/components/_disclaimer.scss
_sass/components/_download_buttons.scss
_sass/components/_goal_tiles.scss
_sass/components/_high_contrast.scss
_sass/components/_language_toggle.scss
_sass/components/_loader.scss
_sass/components/_maps.scss
_sass/components/_notices.scss
_sass/components/_tabs.scss
_sass/layouts/_goal.scss
_sass/layouts/_header.scss
_sass/layouts/_indicator.scss
_sass/layouts/_news.scss
_sass/layouts/_reporting_status.scss
_sass/layouts/_search.scss
_sass/variables.scss
_sass/variables/_colors.scss
_sass/variables/_dimensions.scss
assets/css/style.scss

This is yet another refactorish PR that I'd like to get into version 1.0.0 if possible, though this one should be completely safe, so long as I didn't make any typos. I've gone through the Sass code and converted any colors into Sass variables, which I've put into the _sass/variables/_colors.scss file as "default". This allows users to easily override those variables, by including a _sass/variables.scss file (which we could add to the site starter).
In addition to allowing easier customisation, this opens the door to a future "skins" feature, where we could provide several out-of-the-box skins of the platform, each of which would be a file overriding these Sass variables.
Next steps could include something similar with dimensions (paddings, margins, etc) though I don't intend to try to do …

Convert all colors to "default" Sass variables

---

_sass/components/_breadcrumbs.scss

Fixes #689 
This underlines breadcrumb links, which helps to make the links distinguishable in high-contrast mode, and generally makes it more obvious that they are links.
It also ensures that the last (non-link) breadcrumb is darker (black) when in high-contrast mode (instead of `#333` as it is now).

Underline breadcrumb links

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/model/fieldHelpers.js

This partially address #688. Specifically this makes sure that starting disaggregations will take into account a particular unit, when necessary. What was happening was that a starting unit was getting selected, and then the starting fields were getting selected, but they didn't always match.

Use the selected unit when calculating minimum field values

---

_includes/assets/js/search.js

This was never working apparently, because I used a PHP function instead of the corresponding Javascript function.

Bugfix for search "boost" functionality

---

_sass/layouts/_reporting_status.scss

We have a few Sass variables for the status types, which we're not using:
* $status-backgroundColor-notstarted
* $status-color-notstarted
* $status-backgroundColor-notstarted-highContrast
* $status-backgroundColor-notapplicable-highContrast
This PR adds usage of those variables. It also tweaks our Sass to always use "background" instead of "background-color", so that users can override with more complex backgrounds like gradients.

Use some status-related Sass variables

---

_includes/assets/js/indicatorModel.js
_includes/polyfills.html

@SavvasStephanides This should avoid javascript errors when an indicator has `data_start_values:` in the metadata (without any values).

Safety code for the checks for start values

---

_layouts/reportingstatus.html
tests/data/custom-translations/en/metadata.yml
tests/data/custom-translations/es/metadata.yml
tests/data/meta/1-3-1.md
tests/features/ReportingStatus.feature
tests/features/support/mink.js

Fixes #766 
The reporting status layout was hardcoded to use `site.data.reporting`, which is always populated with the default language. This change looks for translated builds in the current language (eg, `site.data.en.reporting`), and if found, uses that instead. This also adds an automated test for this feature.

Support translations in the reporting status extra fields

---

_includes/components/reporting-status-introduction.html
_layouts/reportingstatus.html
_sass/layouts/_reporting_status.scss
docs/configuration.md
tests/data/custom-translations/en/custom.yml
tests/data/custom-translations/es/custom.yml
tests/data/custom-translations/fr/custom.yml
tests/features/ReportingStatus.feature
tests/site/_config.yml

Fixes #638 
Here is a screenshot:
@phillipgardiner What do you think? I used the "lead-copy" class to make the intro text a bit bigger, like in the frontpage banner.

Configurable reporting status title and description

---

_includes/assets/js/menu.js

In #762 we made a change to an include file, scripts.html. It didn't occur to me at the time, but if a country were overriding that file, then they would get a Javascript error after upgrading, whenever a user tapped the mobile search button. Since we don't want any breaking changes, we need to always provide backwards compatibility code. This is too late for 1.0.2, but better late than never.
I've put `@deprecated start` and `@deprecated end` around this backwards compatibility code. The idea is that, in version 2.0.0, we would simply delete all chunks of code marked `@deprecated`.

Backwards compatibility for code mobile search button text

---

docs/changelog.md

In my haste I forgot to mention the changed files that countries might be overriding. We've already tagged the release, but it's no big deal, as it's only a documentation change.

1.1.0: Mention changed files that could be overridden

---

_includes/components/goals-introduction.html
_layouts/goals.html
_sass/layouts/_goals.scss
_sass/open-sdg.scss
docs/configuration.md
tests/accessibility/pa11yci-contrast.json
tests/accessibility/pa11yci-desktop.json
tests/accessibility/pa11yci-mobile.json
tests/data/custom-translations/en/custom.yml
tests/data/custom-translations/es/custom.yml
tests/data/custom-translations/fr/custom.yml
tests/features/Homepage.feature
tests/features/LanguageSwitcher.feature
tests/site/_config.yml

This will fail testing at the moment, but demonstrates a quick example of simplifying the goals layout and configuring its intro.

Simplify goals layout and allow configurable intro

---

_sass/layouts/_header.scss

This is a long-standing issue that only seems to happen in Firefox, which I have been meaning to investigate. This is a screenshot of the problem:
This is a screenshot with this PR.
Testing in IE, Chrome, etc will be needed.

Line height fix for Firefox search icon

---

_layouts/goal-by-target.html
_sass/base/_mixins.scss
_sass/layouts/_indicator.scss

Fixes #795 
This updates the goal-by-target layout to only have a link on the indicator name, instead of the whole thing (including the number, tags, etc.)
I did not update the original "goal" layout (the one where the indicators are displayed in a grid, without targets) because that would take more effort. For consistency we may want to do that at some point, although I don't believe many (any?) implementations are still using that layout.

Only link indicator name in goal-by-target

---

_includes/assets/js/indicatorView.js
_includes/components/indicator/indicator-main.html

Fixes #846 
This adds a screenreader-only element with some text describing the current state of the chart/table. Examples of possible announcements are:
* "Chart and table shows no data."
* "Chart and table shows datasets for Female and Male."
* "Chart and table shows datasets for Female and Male. Selected unit of measurement is percent."
* "Chart and table shows datasets for Female and Male. Selected series is [my series name]."

Announce changes to the chart/table

---

_includes/assets/js/indicatorView.js
_includes/components/indicator/data-panes.html
_sass/base/_tables.scss

Fixes #869 and #854 
I'm not 100% clear on the benefits here, but here are the changes in this PR:
1. The up/down arrows are now done with Fontawesome icons instead of with background images. This is intended to fix the DAC complaint in #854.
2. Instead of tabbing to the `<th>` elements for to a sort, the users now tab to a `<span role="button">` element inside the `<th>`. The button is `aria-describedby` a hidden div. (Which will eventually have to be translated.) This is intended to fix the DAC complaint in #869.

Accessibility fixes for sorting tables

---

_layouts/goal-by-target-vertical.html
_sass/base/_mixins.scss
_sass/layouts/_goal-by-target-vertical.scss

This is a rebuild of the `goal-by-target-vertical` layout to address the items in #831 and #832.
Because the markup is completely different here, there may be visual differences, though I've tried to keep them to a minimum. This should be tested for cross-browser issues.
I'm not sure if this approach is exactly what was intended. This approach puts all of the target pieces (number and name) in an `h3` and all of the indicator pieces (number, name, status, and tags) in an `h4`. I also considered, to take the example of the indicators, putting the status/tags outside the heading, and the number/name inside the heading. But here I went with the approach of putting all the pieces inside each heading.
That may be confusing, so here's a pseudo-code version of that.
What I considered:
```
<h3> …
```

Refactor of goal-by-target-vertical for accessibility

---

_includes/search.html
_layouts/goals.html
_sass/base/_typography.scss
_sass/components/_download_buttons.scss
_sass/components/_goal_banner.scss
_sass/components/_goal_tiles.scss
_sass/components/_high_contrast.scss
_sass/components/_language_toggle.scss
_sass/layouts/_header.scss
_sass/layouts/_indicator.scss
_sass/layouts/_reporting_status.scss
_sass/variables/_colors.scss

Fixes #849 
This could use design input, as I arbitrarily chose the colors here. I'm using our link color for the normal focus color, and our button highlight color for the high-contrast focus color. Here's an example of each:
Normal contrast:
High contrast:

More obvious focus colors

---

_includes/search.html
_sass/layouts/_header.scss

Fixes #847 
As part of this some changes to the CSS were necessary, and so I took the opportunity to remove a bit of CSS that did not seem needed. So manual cross-browser testing will be necessary to ensure that the search bar looks the same as before.
This implements the markup changes suggested in #847. There should be no visual or functional change.

Search button outside of label

---

_includes/assets/js/indicatorView.js
_sass/layouts/_indicator.scss

Fixes #855 
The footers below indicator charts/tables (with geographical area, unit of measurement, footnote, etc.) should now be a `<dl>` element with a series of `<dt>` and `<dd>` elements, rather than a series of `<p>` elements like before.

Indicator footer as a definition list

---

_includes/assets/js/indicatorView.js
_includes/assets/js/tabs.js
_includes/components/indicator/data-panes.html
_includes/components/indicator/data-tabs.html
assets/js/sdg.js
docs/configuration.md
tests/site/_config.yml

Fixes #840 
@jwestw @LucyGwilliamAdmin This is ready for review. Because this is a moderately significant bit of javascript and does change the tab behavior, I've got this as an optional feature, `accessible_tabs`. Eventually I would foresee this is the default behavior, but for now I don't want to cause problems for the countries during upgrades.
So, when testing this in a feature branch, you would need to add `accessible_tabs: true` to the _config.yml file.

Custom javascript for better tab accessibility

---

_sass/layouts/_indicator.scss

Final fix for #848 
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/black-table-caption/1-2-1/

Use text-colour for table caption

---

_layouts/search.html
_sass/base/_mixins.scss
_sass/base/_typography.scss
_sass/layouts/_search.scss

Fixes #845 
* Removes the category/path from the search result link
* Adds the indicator/goal number in front of the title in the link
* Fixes the problem with the focus treatment of search results
This relies on a PR for jekyll-open-sdg-plugins: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/51
So testing this would require this in the `Gemfile`:
`gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'numbers-in-search-results'`
Here is a screenshot:

Search results link fixes

---

_includes/components/indicator/header.html
_includes/head.html
_sass/layouts/_indicator.scss

This is an experimental PR intended as a companion to #901 to make the indicator page title and H1 closer to what displays in the search results, in that PR.
Visually nothing should change, but semantically the indicator name is now included inside the H1.
Also the page title (ie, the contents of the browser tabs) will now be the word "Indicator" followed by the number, then a dash and the name. Example:
`Indicator 1.1.1 - Proportion of population below the international poverty line, by sex, age, employment status and geographical location (urban/rural)`.
We could simplify that a bit more by removing "Indicator" and/or the dash. Example:
`1.1.1 Proportion of population below the international poverty line, by sex, age, employment status and geographical location (urban/rural)`
This would …

Full indicator name in the page title and h1

---

_includes/assets/js/search.js
_layouts/search.html
docs/configuration.md
tests/site/_config.yml

This is one more tweak to support the site-config-builder functionality. It is intended to be fully backwards-compatible. So the old syntax will still work:
```
search_index_boost:
title: 10
```
But the documented/recommended syntax will be produced by the site builder, and also works:
```
search_index_boost:
- field: title
boost: 10
```

Backwards-compatible array-style for search_index_boost

---

_layouts/news.html
_layouts/post.html
docs/configuration.md

Fixes #911 
This allows category links to be disabled, with this site config:
```
news:
category_links: false
```

Allow disabling of news category links

---

_includes/assets/js/indicatorView.js
_sass/layouts/_indicator.scss

Fixes #931 
This doesn't use `display: none` because I believe that would mess up our animation. Instead this uses `aria-hidden` which should give the same result.

Use aria-hidden when hiding sidebar

---

_includes/assets/js/plugins/jquery.sdgMap.js
_includes/components/indicator/map.html

Fixes #923 
This just hides the loading image and makes the map unfocusable. Another PR (#925) handles making the tab pane focusable.

Make map unfocusable and remove loading image

---

_sass/base/_typography.scss

Fixes the latest comment in #925

For tab panel focus, only show an outline

---

_sass/components/_maps.scss

Fixes the parts of #900 related to color contrast - I think. Actually #900 might need clarification of the specific color contrast issues. So far this only affects the "attribution" section, in the lower-right corner of the map.

Map color contrast fixes

---

_sass/base/_mixins.scss
_sass/components/_maps.scss

This fixes #955 only in the IE and Edge browsers. In other browsers (like Chrome and Firefox) this will have no effect, but if they ever decide to support the property `forced-color-adjust` property, it will resolve it for them too.

Keep swatch colors in Edge/IE + high-contrast mode

---

_includes/components/indicator/fields-template.html

Fixes #964 
Though this looks like a lot of changes, it is really just moving a couple of elements (`fieldset` and `legend`) from one spot to another. Because the indentation changed, a lot of lines appear changed. Moving markup does carry the risk of messing up some CSS styling and/or javascript. I tested locally and it seemed OK.

Move fieldset/legend to different spot in markup

---

docs/configuration.md
docs/data-configuration.md
mkdocs.yml

@LucyGwilliamAdmin @jwestw Our documentation of the various data config settings is a bit obscure right now, being buried in the sdg-build library. What do you think about adding it to the Open SDG docs, like in this PR?
The only downside is that if we change the way sdg-build works, we'll need to remember to update these docs. But personally I'm OK with that, if it means we have better documentation overall.

Documentation of data repository configuration

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js
_includes/components/indicator/indicator-main.html
_includes/scripts.html

Fixes #194 
This is intended to allow for download buttons for indicator-specific SDMX files, although it is general-purpose and any indicator-specific file downloads. Testing is possible, though a little tricky because it depends on PRs in sdg-build and jekyll-open-sdg-plugins. I still need to add documentation to this PR, but here are the steps to test:
1. Add something like this to the data repository config (this would be the config to add a download button for CSV files):
indicator_downloads:
- button_label: indicator.download_source
source_pattern: data/indicator_*.csv
indicator_id_pattern: indicator_(.*)
output_folder: data-csv
2. Change the data repository requirements.txt to point to my fork of sdg-build:
git+git://github.com/brockfanning/sdg-build-1@indicator-downloads
3. Change …

Custom source-file downloads

---

.gitignore
Makefile
_includes/assets/js/indicatorView.js
_includes/assets/js/model/fieldHelpers.js
_includes/assets/js/model/helpers.js
_sass/base/_mixins.scss
_sass/components/_language_toggle.scss
_sass/layouts/_goal-by-target.scss
_sass/layouts/_header.scss
_sass/open-sdg.scss
docs/changelog.md
docs/updates.md
docs/upgrades/upgrading-1-2-0.md
mkdocs.yml
tests/features/Search.feature
tests/package.json
tests/release/back-compat.js

EDIT: Since I'm adding fixes and changelog updates to this PR, this can be a general 1.2.0 preparation PR.
This is a helper script to test the behavior of the codebase when a single file is reverted to the 1.0.0 version. It's intended to reveal potential breaking changes in the case that an implementation has overridden that file. Using this will be a very manual process, because many times the tests will fail for some reason that does not mean there is a breaking change. The usage would be something like this:
```
node tests/release/back-compat.js _layouts/goal.html
```
The above would look for breaking changes in the goal.html layout. We would need to run this script for every single file that has changed, so it will still be a time-consuming process, just a bit easier.

1.2.0 release prep

---

_includes/components/indicator/data-tabs.html
_sass/base/_typography.scss
_sass/components/_tabs.scss
_sass/layouts/_indicator.scss
_sass/variables/_colors.scss

@phillipgardiner Can I get your feedback on this? I can't remember if we've discussed this. My thinking is that, since tab focus is activated constantly by all users (just by using the tabs) that it might be a good idea to have it be a bit more subtle - with a yellow outline instead of a full yellow background (which it is inheriting by virtue of being a link). Here's a before/after for this PR:
Before:
After:

Tab focus design fixes

---

_includes/assets/js/accessibleTabs.js
_includes/assets/js/tabs.js
assets/js/sdg.js

We recently changed the styling of tabs so that only the text gets highlighted. Unfortunately this means that the rest of the tab no longer has the click behavior. This tweak is intended to fix that.
We already had a "tabs.js" file but it was only being loaded if "accessible_tabs" was on. So this PR renames that file to accessibleTabs.js and puts the new behavior in tabs.js.

Allow click around tab link to trigger tab

---

_sass/layouts/_frontpage.scss
_sass/open-sdg.scss

This fixes a slight regression bug, and would be good to get merged before 1.2.0. The bug only affects the "frontpage" layout (no longer used by the starter repos which are now using the "frontpage-alt" layout, but still used by multiple countries). The margin beneath the goal tiles on the homepage was missing. Here are before and after screenshots:
Before:
After:

Bottom margin on frontpage goal tiles

---

_includes/assets/js/tabs.js

The recently-merged tab fix (#1012) unfortunately broke tab functionality for sites with accessible_tabs set to false. This should fix that.

Fix tab clicking when accessible_tabs is false

---

_includes/assets/js/model/helpers.js

This helper function is used in indicatorModel.js, but is not actually present in the "helpers" object. So this is a bug - a bit hard to test because of all the conditions to satisfy - but clearly in need of fixing.

Series helper function bug fix

---

_includes/components/goal/goal-content.html
_layouts/goal-by-target-vertical.html
_layouts/goal-by-target.html
_layouts/goal.html
docs/configuration.md
tests/data/custom-translations/en/custom.yml
tests/data/custom-translations/es/custom.yml
tests/data/custom-translations/fr/custom.yml
tests/features/Goal.feature
tests/site/Gemfile
tests/site/_data/site_config.yml

Fixes #631 
This depends on a PR on jekyll-open-sdg-plugins, so needs this in the Gemfile for the site repository:
```
gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'goal-content-configuration'
```
Add to the "create_goals" site configuration, like so:
```
create_goals:
layout: goal
goals:
- content: My goal content for goal 1
- content: "My goal content for goal 2, with [a link](https://example.com)"
- content: custom.my_translation_key
```
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/goal-content

Support for goal content

---

tests/package.json

All new PRs are failing because of something that's going on in the latest version of Cucumber, so we need to pin to an old version for now and upgrade when possible.

Pin to earlier version of Cucumber for now

---

_includes/assets/js/indicatorView.js
_includes/assets/js/plugins/jquery.sdgMap.js
_layouts/config-builder.html
_sass/layouts/_config_bulder.scss
tests/site/Gemfile

This attempts to address the items in #1000. Changes include:
* Remove all "table formatting" (ie, fields in rows) and instead display all fields vertically
* Remove the Markdown editor and show plain text areas instead
* Labels for integer fields (eg "Goal color number")
* Adds a message to links about opening in a new tab (screenreaders only)
* Use a button for the search filter
* Adds screenreader status announcement of search filter results
This also fixes IE support in general, which had been broken by recent changes.
A couple of items from #1000 are not fixed here:
* Item 4 - related to color fields: Since we're only using the standard HTML5 input for color, I would want to get confirmation that we actually need to remove those.
* Items 2 and 9 (I think these are the same right?): …

Configuration form accessibility fixes

---

_sass/base/_tables.scss
_sass/layouts/_goal.scss
_sass/layouts/_indicator.scss

Addresses the suggestion from here: https://github.com/open-sdg/open-sdg/pull/1005#issuecomment-748045038
The screenshot below is with 30px margin beneath, and -20px margin above (it needs a negative margin in order to pull it closer to the goal banner).
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/goal-content/1/

Tweak page-content styles for goal pages

---

_includes/assets/js/indicatorView.js
_includes/components/charts/binary.html
_includes/javascript-variables.html

Fixes #1013 
We already allow alteration of Chart.js configuration through the `opensdg.chartConfigAlter` function. Along the same lines, this allows alteration of the DataTables configuration through `opensdg.tableConfigAlter`. A possible use-case might be changing the display of some data value to a more human-friendly version.
To demonstrate this also fixes issue #1013 by converting "1" into "Yes" and "-1" into "No" in the "binary" graph type.
Note: This requires a data branch - will need to change graph_type to binary and make sure data complies to requirements set out here: https://open-sdg.readthedocs.io/en/latest/charts/#binary

Allow alteration of DataTable configuration and fix tables for "binary" indicators

---

_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.yearSlider.js

Fixes #108 
Currently a "Year" in data can be non-numeric, like "2017-2019" for example. This works fine for charts and tables, but it breaks the maps. This attempts to provide better support for maps. The years must still *start* with a year, but can include anything else. For example this code should allow for the following year values:
* 2017-2018
* 2017.4
* 2017 Q4
* 2017/4
Note: For testing this will involve creating a data branch too - will need to change a data file for an indicator that has a map e.g. 3.a.1 so that values in year column have something other than the year (don't need to change all though - just headline)
[Feature Branch - indicator 3-a-1](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/non-numeric-years/3-a-1/)

Support non-numeric years in maps

---

_includes/assets/js/model/fieldHelpers.js

The `validParentsByChild` function can be a bottleneck in large datasets with a lot of disaggregation values, because of all the loops and filtering. This is a minor optimization of it that should help some. This moves some calculations outside of a loop to reduce the number of times it has to run.
Here is a before/after comparison using UK's 4.2.1:
Total: 959.3ms
Total: 521.9ms
So this optimization saves a little less than half a second. Not a huge improvement, but at least something. It should be noted that 521.9ms is still a _lot_ for a javascript function, so there is still room for improvement (like seeing if this function can be avoided altogether in some way).
Testing should focus on making sure that:
1. Indicators with lots of data and disaggregation load a bit faster
2. …

Optimization of validParentsByChild

---

_includes/head.html

Right now our html `lang` attribute is hardcoded as "en". I'm not aware of any reason we would not want it to be dynamic, based on the current language.
[Feature Branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dynamic-lang-att2)

HTML 'lang' attribute should depend on current language

---

_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.selectionLegend.js

Fixes #899 
By itself this doesn't change anything, since the [default dataRounding function](https://github.com/open-sdg/open-sdg/blob/master/_includes/javascript-variables.html#L16-L19) does no rounding. But if this rounding function has been customized, this PR applies it to the map data.
Since the UK has a [dataRounding function](https://github.com/ONSdigital/sdg-indicators/blob/develop/assets/js/custom.js), this can be tested on a UK feature branch if any map data has decimals to check.
[Edit: Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/map-data-rounding)

Round the map data

---

Makefile

Fixes #623 
This is a test-only fix, and so doesn't need testing.

Avoid installing npm unless running tests

---

_sass/layouts/_indicator.scss
tests/data/meta/1-1-1.md
tests/features/Indicator.feature

This is a fix for one of the issues mentioned in #504 -- namely the problem where the placement of the odd-numbered sources is inconsistent depending on the height of the even-numbered sources. This change forces odd-numbered sources to always align to the left.
There is another issue mentioned in #504 -- namely the incongruity of the horizontal lines when different-height fields are next to each other -- which needs a design discussion, so is not addressed here.
Testing note - if using a feature branch, the UK's indicator 5-5-1 is a good one to test.

Fix layout issues with odd-numbered indicator sources

---

_includes/assets/js/accessibility.js
_includes/components/indicator/header.html
_includes/components/reportingstatus/reporting-status-by-goal.html
_layouts/frontpage-alt.html
_layouts/frontpage.html
_layouts/goal-by-target-vertical.html
_layouts/goal-by-target.html
_layouts/goal.html
_layouts/goals.html

Because SVG images can use CSS styling, there is no need to change them for high-contrast. So this PR skips the image-changing behavior for SVG icons.
Also, this PR adds some useful HTML classes to all goal icons throughout the site. They aren't used anywhere, and won't affect anything, but may be useful in the future, or to any countries that would like to add special styling to goal images.
EDIT: [Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/svg-icon-high-contrast/)

Do not change SVG images in high-contrast mode

---

_includes/components/reportingstatus/reporting-status-by-field.html
_includes/components/reportingstatus/reporting-status-by-goal.html
_includes/components/reportingstatus/reporting-status-overall.html
_sass/components/_high_contrast.scss
_sass/layouts/_header.scss
_sass/layouts/_reporting_status.scss

Partial fixes for #989 
In this PR:
1. Move spans outside of headings on reporting status page - style changes to match
2. Line-height-related fixes for better support of zooming in
3. Preserve some background colors in Windows high contrast mode in IE/Edge
Some of the things mentioned in #989 are not yet in this PR - I'll post my thoughts over there.
EDIT: [Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/reporting-status-accessibility-fixes/reporting-status/)

Reporting status accessibility fixes

---

_includes/title-tag.html

When using the config forms, empty values are saved as empty strings (`''`). But these are being placed in the page title, so it ends up like: `- Indicators for the Sustainable Development Goals`. This extra check avoids that, so it will properly be `Indicators for the Sustainable Development Goals`.
If you would like to test this one, you could try giving an empty title to the homepage. Eg:
```
create_pages:
- folder: /
layout: frontpage
title: ''
```
EDIT: [Feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/skip-empty-titles)

Do not use empty titles in head

---

_layouts/config-builder.html

@LucyGwilliamAdmin @jwestw This is a straightforward bugfix -- "choices" is not a variable there, it was meant to be "dropdown".
I don't think this is worth a feature branch.

Bug fix - variable name in config builder

---

_layouts/config-builder.html

This is a quick change to avoid "mixed content" errors in browsers. Some (all?) browsers do not like it when a page loads some assets using "https" and others using "http", and they will block the "http" assets.
I don't think this is worth a feature branch.

Use https to avoid mixed content error

---

tests/data/data/indicator_3-1-1.csv
tests/data/requirements.txt

This is intended to demonstrate that https://github.com/open-sdg/sdg-build/pull/198 is working. When pointing at that PR's branch, the tests here pass. But when pointed back at 1.3.0-dev, the tests fail.
After https://github.com/open-sdg/sdg-build/pull/198 is merged, the tests here can be re-run and they should pass, at which point this can be approved/merged.

Allow numeric disaggregation

---

_sass/base/_mixins.scss
_sass/layouts/_goal-by-target-vertical.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/high-contrast-status-notstarted-outline)
Fixed issues | #1108

Fix reporting status type styling in goal-by-target-vertical

---

pull_request_template.md

@LucyGwilliamAdmin  A tweak to the PR template - I realized that the test item was needed after all. And also thought maybe docs and forms could be on separate lines?

Add note item for tests and split docs/forms

---

_layouts/search.html
tests/data/custom-translations/es/search.yml
tests/features/Search.feature

Fixes #236 
Testing this in a non-English language is quite tricky and would involve a lot of extra steps. I would recommend only testing that this works in English. If it works in English, it will work in other languages (once they are translated).
To test, do any search and look for a "Results found: X" message.  If it does not appear, then it's not working right.

Translate 'Results found'

---

_sass/variables/_colors.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/chart-color-accessibility-revamp)
Fixed issues | #1100
Bugfix, feature or docs? | feature

Tweak the link/visited colors in high contrast mode

---

_includes/assets/js/search.js
docs/changelog.md

Q | A
--- | ---
Fixed issues | #979 
Added CHANGELOG entry? |✔️
1. Configure site to use multiple languages
2. Visit site in a non-English language (I've tested in Spanish)
3. Do a search for "1.1.1"
4. Confirm that 1 result is shown
Without this PR, 0 results will be shown.

Do not use Lunr for indicator id searches

---

_sass/base/_typography.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/high-contrast-focus-outside-chart)
Fixed issues | Fixes #1109

Avoid highlighting entire div on focus

---

_sass/layouts/_indicator.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/high-contrast-dropdown-focus-color)
Fixed issues | #1107

Fix focus color on dropdowns in high-contrast

---

_includes/assets/js/chartColors.js
docs/changelog.md
docs/configuration.md

Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/accessible-chart-colors/)
Fixed issues | #1099
Updated docs/config-forms? |✔️
Added CHANGELOG entry? |✔️
Site configuration:
```
graph_color_set: accessible
```

New 'accessible' option for chart colors

---

_sass/layouts/_indicator.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/high-contrast-chart-legend-hover/)
Fixed issues | Fixes #1105

Remove hover styles for high-contrast chart legend

---

.github/workflows/test-pull-requests.yml

This is needed because Github Actions is migrating to Ubuntu 20.04, but our test suite fails in those cases with random "Page crashed" errors from Puppeteer.

Pin to Ubuntu 18.04 because 20.04 doesn't work for tests

---

_sass/base/_tables.scss
_sass/layouts/_indicator.scss
_sass/variables/_colors.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](https://lucygwilliamadmin.github.io/sdg-indicators/1-2-1/)
Fixed issues | Fixes #1113 
Keeps backward-compatibility? |✔️(technically is a change but very minor)

Standard background color for hovering over table rows and field options

---

.readthedocs.yaml
Makefile
docs/requirements.txt

Mkdocs just released 1.2 which is failing tests. I think it needs some extra configuration, but a quick fix is to pin to the known working version 1.1.2, which is a good practice anyway. We can upgrade to 1.2 in the future if there is some feature we need. This also adds a readthedocs config file which should ensure that readthedocs uses that pinned version.

Pin to mkdocs 1.1.2

---

docs/automation/github.md
docs/automation/triggered-site-builds.md
docs/quick-start.md
tests/site/_data/site_config.yml

These are documentation updates to get a simpler quickstart. These depend on two other PRs:
* https://github.com/open-sdg/open-sdg-site-starter/pull/75
* https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/102
Since there a lot of changes here are links directly to the new versions of the 3 files:
* https://github.com/brockfanning/open-sdg/blob/quick-start-revamp-1-4-0/docs/quick-start.md
* https://github.com/brockfanning/open-sdg/blob/quick-start-revamp-1-4-0/docs/automation/github.md
* https://github.com/brockfanning/open-sdg/blob/quick-start-revamp-1-4-0/docs/automation/triggered-site-builds.md

Quick start revamp 1.4.0

---

docs/configuration.md
tests/site/_data/site_config.yml

This depends on https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/101
Q | A
--- | ---
Bugfix, feature or docs? | docs
Updated config forms? |✔️
These 2 new config settings may be useful in the future for various purposes, but the immediate purpose is to allow for a smoother quickstart process. As we switch to using the config forms in the quickstart, we'll need to populate the "repository_link" settings, to enable the "Go to repository" links on the forms. This feature is critical to the user-friendliness of the forms, in my opinion.
With these new settings, a new user would only need to …

Document repository_url_data and repository_url_site fields

---

docs/architecture.md
docs/requirements.md

This is a docs update to refresh the third-party libraries that are used. This also starts the process of removing/replacing a couple of references to Prose.io (since we now have built-in forms for data and metadata).

Requirements updates (docs)

---

_includes/assets/js/plugins/jquery.sdgMap.js
_sass/components/_maps.scss

Q | A
--- | ---
Fixed issues | Fixes #1194
This has a quick fix to a couple of zoom-related issues mentioned in #1194:
1. On small-screens/high-zooms the attribution element has a max-width of 100px and aligns to the right
2. Even when loaded on small-screens/high-zooms, the map will never be shorter than 400px high.

Quick fixes for some zoom issues on maps

---

_includes/search.html

Q | A
--- | ---
Feature branch/test site URL | [Link](https://1-4-0-site.github.io/)
Fixed issues | Fixes #1254 

Add slash after 'search' in URL

---

_includes/components/reportingstatus/reporting-status-label.html
_sass/base/_mixins.scss
_sass/components/_goal_tiles.scss
_sass/layouts/_reporting_status.scss

Q | A
--- | ---
Feature branch/test site URL | [Link (goal-by-target-vertical)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-na-style/1/)<br>[Link (goal-by-target)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-na-goal-by-target/reporting-status/)<br>[Link (goal)](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-na-goal/1/)
Fixed issues | Fixes #1239 
Disclaimer: Our styles for these elements are kind of a mess. I've tried to clean things up a little in this PR. But this means that I may have broken something else, so I think that this should be tested with a critical eye towards anything that involves the status types:
* goal layout
* …

Not applicable - white background on goal pages

---

_includes/components/post/post-listing.html
_layouts/post.html
_sass/base/_mixins.scss
_sass/components/_goal_tiles.scss
_sass/layouts/_goal-by-target-vertical.scss
_sass/layouts/_goal-by-target.scss
_sass/layouts/_goal.scss
_sass/layouts/_indicator.scss
_sass/layouts/_news.scss
_sass/layouts/_post.scss
_sass/layouts/_reporting_status.scss
_sass/open-sdg.scss
_sass/variables/_colors.scss

Fixes #1325 
Fixes #1326 
Q | A
--- | ---
Feature branch/test site URL | [goal-by-target-vertical](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-status-style-revamp-take-2/)</br>[goal-by-target](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-status-style-revamp-take-2-goal-by-target/)</br>[goal](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-status-style-revamp-take-2-goal/)
Fixed issues | Fixes #1325 and #1326
This is a further revamp of the status styles. I think there is way more we could do, but it would be too much for now. To test this thoroughly, I would recommend 3 separate feature branches, with all three types of goal pages:
```
create_goals: …
```

Another status style refactor and post category fixes

---

_includes/components/favicons.html
docs/configuration.md

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-1.5.0-beta1/)
This is to avoid a breaking change. We'll have the starter repos use the `favicon.io` setting, even though the default will be `legacy` so that existing sites' favicons don't break.
Corresponding PR for the config setting: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/111

Add setting for favicons to default to legacy

---

_includes/cookies-config.js

Q | A
--- | ---
For Google Analytics cookies, I believe that it should be "_ga" instead of "ga", judging from: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage

Google Analytics: _ga instead of ga

---

_sass/layouts/_goal-with-progress.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-remove-tag-margin-bottom/1/)
Fixed issues | Fixes #1407 
Related version | 1.6.0-beta1
This removes the 10 pixel margin bottom that was present on all lists, from the list of tags on the goal-with-progress layout.

Remove bottom margin from tags in goals-with-progress layout

---

_includes/components/reportingstatus/reporting-status-by-field.html
_includes/components/reportingstatus/reporting-status-by-goal.html
_includes/components/reportingstatus/reporting-status-overall.html
_layouts/reportingstatus.html

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-disaggregation-status-types)
Fixed issues | Fixes #1397 
Related version | 1.6.0-beta1
This PR depends on two other PRs:
* https://github.com/open-sdg/sdg-build/pull/281
* https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/115
This moves translations of disaggregation status types out of sdg-build so that it works with the new layout.

Use different status types for disagg status

---

_layouts/page-not-found.html
_sass/layouts/_page-not-found.scss
_sass/open-sdg.scss
docs/changelog.md
tests/site/_pages/page-not-found.md

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-custom-404-page/404.html)
Fixed issues | Fixes #1276 
Bugfix, feature or docs? | feature
To test this, the steps would be:
1. Point to this branch
2. Create a file in the _pages folder.
3. Copy the text below into the file.
4. Update the Github Pages settings according to these docs: https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site
(use "404.html" as the filename)
```
---
layout: page-not-found
title: Page not found
permalink: 404.html
---
If you typed the web address, check it is correct.
If you pasted the web address, check you copied the entire address.
If …
```

Custom 404 page

---

_sass/bootstrap5/layouts/_indicator.scss

Quick fix of chart background color when focused (clicked on) in high-contrast mode. The chart should only have a yellow outline; not a full yellow background.

Specificity fix for chart focus in high-contrast

---

_includes/assets/js/chartjs/rescaler.js
_includes/assets/js/indicatorView.js
assets/js/sdg.js

This recovers the "rescaler" plugin which had been removed. This plugin is responsible for "cropping" the chart datasets so that empty years at the beginning/end of each dataset are not shown. This ensures that the chart will take up all the available space.
This PR also adds a bit of documentation and simplifies the code a bit, to avoid confusion in the future.
This show work whether `chartjs_3` is true or false.

Recover rescaler

---

_includes/assets/js/bootstrap5/accessibleTabs.js

Quick fix for accessible tabs if bootstrap_5 is enabled. Without this fix users cannot use the tab key to navigate to the Chart/Table/etc tabs.

Bootstrap5 accessible tabs fix

---

_includes/assets/js/chartjs/accessibleCharts-chartjs3.js
_includes/assets/js/indicatorView.js
_includes/assets/js/view/chartHelpers.js
_includes/bootstrap5/components/header.html
_includes/components/charts/chart.html
_includes/components/header/header-default.html
_includes/components/header/header-menu-left-aligned.html
_includes/components/indicator/data-footer.html
_includes/components/indicator/fields-template.html
_includes/components/indicator/indicator-main.html
_includes/components/indicator/metadata.html
_includes/components/indicator/series-template.html
_includes/components/indicator/tags.html
_includes/components/indicator/units-template.html
_sass/bootstrap5/base/_screenreaders.scss
_sass/open-sdg-bootstrap5.scss

The recent Bootstrap 5 upgrade changed a lot of files, but a large proportion of them were only changing the "sr-only" class to "visually-hidden". We can just keep support for "sr-only" with a few lines of CSS, and not have to change a lot of files. This should make the upgrade process easier for users.

Keep sr-only class to avoid unneeded file changes

---

_includes/components/indicator/map.html
_sass/bootstrap5/layouts/_indicator.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-map-title-should-not-react-to-series-changes/3-3-3/)
Fixed issues | Fixes #1600 

Do not change map title when series changes

---

_sass/layouts/_default.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-less-top-padding-on-main-content/)
Fixed issues | Fixes #1624 

Remove top padding on main-content

---

_includes/components/goal/header.html
_sass/layouts/_goal.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-goals-page-icon-floating)
Fixed issues | Fixes #1621 

Do not float icon on goal page on mobile

---

_sass/components/_card.scss
_sass/components/_frontpage_cards.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-frontpage-section-margin-mobile/)
Fixed issues | Fixes #1620 

Less space above frontpage card sections

---

_sass/base/_no_javascript.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-no-js-navigation-fixes/)
Fixed issues | Fixes #1653 
This PR changes has 3 effects when javascript in not available:
1. The hamburger menu is expanded
2. The hamburger toggle is hidden
3. Navigation drop-downs are hidden
The 3rd item is a temporary measure to hide a non-functional feature. The ultimate fix will be done later in this ticket: #1654

For no-js: hide hamburger toggle, expand hamburger menu, hide drop-downs

---

_includes/components/indicator/data-footer.html

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-footer-fields-test/1-1-1/)
Fixed issues | Fixes #1651 

Handle null values in current series/unit for footer fields

---

_includes/assets/js/chartjs/accessibleCharts.js
_includes/assets/js/chartjs/noDataMessage.js
_includes/assets/js/view/chartHelpers.js

This should fix a few random chart-related things that I've noticed:
To replicate:
1. Open the developer console
2. Go to an indicator in which you can get the no-data message (ie, "This data is not available. Please choose alternative data to display.")
3. Click on the no-data message
4. Wait a few seconds and notice the infinite loop in the developer console
To replicate:
1. Switch to high contrast
2. Go to an indicator in which you can get the no-data message (ie, "This data is not available. Please choose alternative data to display.")
3. Notice that the no-data message is not visible
To replicate:
1. Turn on a screenreader
2. Go to an indicator with disaggregation
3. Tick any disaggregation checkbox
4. Notice there is no screenreader announcement
In addition to testing the three …

Various chart-related fixes

---

_includes/components/indicator/data-footer.html

This is a small and straightforward fix, so there is no issue for it. A closing HTML tag just needs to be fixed. This is causing an alert in an accessibility audit, mentioned in #1593.
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-nested-dl-accessibility-fix/)

Fix closing tag in data footer

---

_includes/assets/js/cookieConsent.js

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-cookie-setting-tab-index)
Without this PR, it is impossible to get to the "Cookie settings" link in the footer using a keyboard. (Note @otis-bath that this link is not applicable on the UK site because of the different way that cookie consent is handled, so this might be a tough one to test.)
Mentioned in #1593

Allow keyboard access to cookie settings link in footer

---

_includes/components/indicator/headline.html
_sass/base/_no_javascript.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-no-js-headline-fixes/)
Fixed issues | Fixes #1616 

No-javascript tweaks related to headline data

---

_layouts/config-builder.html

This is a duplicate of #1660 but for 1.8.0, so that we can release a hotfix for that.

Hotfix for 1.8.0 - Pin to 2.6.1 of json-editor

---

_layouts/reportingstatus.html

This should help with: https://github.com/open-sdg/open-sdg/issues/1593#issuecomment-1157478708
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-status-tab-controls-fix/)

Fix aria-controls attributes on reporting status page

---

_includes/assets/js/plugins/leaflet.selectionLegend.js
_sass/components/_maps.scss
_sass/variables/_colors.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-selection-legend-text-to-the-left/3-3-4/)
Fixed issues | Fixes #1677 
This changes the markup and styling of the "selection legend" on maps, so that the names of regions appear to the left of the horizontal bar. It also changes from `<ul>` tags to `<dl>` tags, which is a bit more semantically correct.

Selection legend revamp moving name to the left

---

_includes/assets/js/chartColors.js
docs/configuration.md

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-default-to-accessible-chart-colors/)
Fixed issues | Fixes #1681 
@phillipgardiner @otis-bath @LucyGwilliamAdmin This actually is not just a documentation issue - we actually forgot to make "accessible" the new default. So I think this should go into 2.0.0, if possible.
The PR changes "accessible" to be the default, and also changes the old "default" colorset to be called "classic". If a site was previously configured to be "default", with this PR that site will now display the accessible colors. Sites who want to continue using the old default can configure their site to "classic".

Default to accessibile chart colorset

---

_includes/assets/js/view/chartTypeBase.js

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-draw-annotations-after-datasets/)
Fixed issues | Fixes #1683 
@phillipgardiner @otis-bath @LucyGwilliamAdmin This could help with #1683 and possibly #1684 too. If you would like, this could be added for 2.0.0 as a bug.
I would recommend testing this with at least four scenarios:
1. Line chart with a target line
2. Bar chart with a target line
3. Line chart with a series break
4. Bar chart with a series break
It's possible this may prompt other changes. Here is what it looks like locally with the 2nd scenario above:

Draw annotations after datasets

---

_includes/components/dev-disclaimer.html
_includes/components/indicator/metadata-panes-default.html

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-translation-replacement-fixes/1-1-1/)
Fixed issues | Fixes #1702 
This fixes the "parameter-replacement" in the default dev disclaimer and the default national metadata blurb. This needs the latest jekyll-open-sdg-plugins code from branch 2.0.0-dev.

Translation replacement fixes

---

_includes/assets/js/plugins/jquery.sdgMap.js

Q | A
--- | ---
Fixed issues | Fixes #1713 
This PR adds some quick safety code to prevent an out-of-index error when a particular map reason has fewer disaggregations than others. Though I don't know why that would happen, so there may be a deeper investigation to do there, on the sdg-build side. But in the meantime, this avoids the error and should display no data for that part of the map.

Map disaggregation index bug

---

_includes/assets/js/model/dataHelpers.js
_includes/javascript-variables.html
tests/data/custom-translations/en/custom.yml
tests/data/data/indicator_1-2-1.csv
tests/features/Disaggregation.feature
tests/site/_data/site_config.yml

Q | A
--- | ---
Fixed issues | Fixes #1722 
This depends on a pull-request in jekyll-open-sdg-plugins: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/140
Tests here will fail until that PR is merged.
To test this manually:
1. Add a column to an indicator's data that uses a translation key. For example, the first line of a CSV file might be: `Year,custom.my_translation_key,Value`
2. Configure the site config's `ignored_disaggregations` to have the same translation key, eg: `ignored_disaggregations: ['custom.my_translation_key']`
3. Confirm that the column does *not* appear as a disaggregation dropdown (ie, confirm that it gets ignored)

Support translation keys in the ignored_disaggregation site config

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js
_includes/assets/js/mapView.js
_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.disaggregationControls.js
_sass/components/_maps.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-map-series-unit-behaviors/3-3-3/)
Fixed issues | Fixes #1723 
1. Pick an indicator that has series, units, and geocodes
3. Enable maps for that indicator's config
data_show_map: true
4. Enable the map disaggregation option in site config
map_options:
disaggregation_controls: true
5. Configure graph titles, precision, and footer_fields to be dependent on the series
6. Confirm that, on the map, changing the series has the expected effects
7. Confirm that, on the map, changing the unit updates the footer field

Map series/unit behaviors

---

_includes/assets/js/view/chartHelpers.js

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-y-axis-line-wrapping/1-5-1/)
Fixed issues | Fixes #1693 
This automatically wraps the Y axis label to 40 characters per line. I'm assuming that the height of the chart is predictable, so we can just hardcode the limit at 40. We should test this with a variety of charts to make sure that assumption is OK to make.

Wrap Y axis labels to 40 characters per line

---

_includes/assets/js/chartjs/accessibleCharts.js

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-chart-keyboard-navigation-fix/15-2-1/)
Fixed issues | Fixes #1756
Note on testing: This problem only happens after switching to a different series. To see the problem:
1. Go to https://onsdigital.github.io/sdg-indicators/15-2-1/
2. Click on the chart
3. Note that you can use the right-arrow on your keyboard to cycle through all 8 data points
4. Switch to the "Above-ground biomass stock" series
5. Note that there are now 9 data points
6. Click on the chart
7. Note that when using the right-arrow, you can't get to the 9th data point
If you put this PR on a feature branch, you should be able to go through …

Refresh keyboard navigation plugin on chart update

---

_includes/assets/js/view/seriesHelpers.js

Q | A
--- | ---
Fixed issues | Fixes #1757 
To recreate the problem:
1. Go to https://onsdigital.github.io/sdg-indicators/15-2-1/
2. Press the TAB key until "Woodland area net change" has focus
3. Press the down arrow to switch to "Above-ground biomass stock"
4. Press the down arrow again
5. Note that it does not switch to the next series, and instead just scrolls the page a bit
If you make a feature branch with this PR, after step 4 it should switch to the next series ("Percent of woodland within protected areas").

Maintain focus when changing series

---

_includes/assets/js/plugins/leaflet.yearSlider.js

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-slider-aria-fix/3-3-3/)
Fixed issues | Fixes #1755
Testing notes: In order to test this, you can either inspect the map's play-button element in the browser's developer console, and confirm that its title attribute changes to "Pause" while it is playing. Or I believe you could also use a screenreader to test it, but I'm not sure exactly how it should behave.

Update title of map play/pause button dynamically

---

_includes/components/indicator/metadata.html
_sass/layouts/_indicator.scss
_sass/variables/_colors.scss
docs/configuration.md

This relies on a PR in sdg-translations: https://github.com/open-sdg/sdg-translations/pull/297
To test the default ("Not available for this indicator"), you don't need to use the new config. Just make sure that `hide_empty_metadata` is false:
```
hide_empty_metadata: false
```
To test a custom placeholder, you also need to use the new site config:
```
hide_empty_metadata: false
empty_metadata_placeholder: My placeholder
```
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-empty-metadata-placeholder)
Fixed issues | Fixes #1726 

Placeholder for empty metadata

---

_includes/components/indicator/metadata.html
_sass/components/_metadata.scss
_sass/open-sdg.scss

This is meant to fix the second issue mentioned in #1761. It only has an effect on 500 pixels width and narrower, so this should only affect phones, and browsers on high zoom. To confirm I would recommend testing a variety of indicator metadata on:
1. Normal desktop
2. Desktop zoomed to 400%
3. Phones
Things to look out for include:
* Metadata that is overflowing outside of the column
* Metadata that seems too narrow to read
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-zoom-metadata-overflow-fix)
Fixed issues | Fixes #1761 

Fix for metadata content overflow on high magnification

---

_includes/components/download-all-data.html

This PR depends on an sdg-translations PR: https://github.com/open-sdg/sdg-translations/pull/290
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-download-button-update/1-1-1/)
Fixed issues | Fixes #1727 

Update data download card to use new translations

---

_includes/components/indicator/embedded-feature.html

This markup should not be here - must have been a copy/paste error.

Remove extraneous markup

---

_includes/assets/js/plugins/leaflet.disaggregationControls.js

For any indicator with a map, add a new column in the data, and give each row the same value. For example add a new column called "Foo" and give each row a value of "Bar" in that column.
Without this PR, that new disaggregation value ("Foo: Bar") will *not* appear in the lower-left map disaggregation box. But with this PR, it should appear.
If you would like to test the button for changing the map disaggregations, the site configuration for that is "disaggregation_controls" under "map_options", as shown here: https://open-sdg.readthedocs.io/en/latest/maps/#map_options (it needs to be "true" for the button to appear)
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-map-identify-region-column …

Better pruning of map disaggregations to hide region columns

---

_includes/components/goal/goal-content.html

Update the site config `create_goals` setting to include a `goal_content_heading` property. For example, to show some content on goal 1 with a heading, you could use this:
```
create_goals:
previous_next_links: false
goal_content_heading: 'My heading for goal content'
goals:
- goal: '1'
content: 'My content for goal 1'
```
I believe this relies on the latest jekyll-open-sdg-plugins code (2.1.0-dev branch). So the Gemfile needs to have:
`gem 'jekyll-open-sdg-plugins', git: 'https://github.com/open-sdg/jekyll-open-sdg-plugins.git', branch: '2.1.0-dev'`
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-goal-content-heading-config/2/)
Fixed issues | Fixes #1746 …

Support for goal_content_heading site config

---

_sass/layouts/_page.scss
_sass/layouts/_post.scss
_sass/open-sdg.scss

This PR adds more margin above any H2 elements within the content of 'page' and 'post' layouts.
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-content-h2-margin-top/publications/)
Fixed issues | Fixes #1631 

More margin above H2 when it is in content of 'page' and 'post' layouts

---

_includes/assets/js/accessibility.js
_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.searchAccessible.js
_includes/assets/js/plugins/leaflet.yearSlider.js
_includes/assets/js/view/utils.js
_includes/components/charts/chart.html
_includes/components/goal-tiles.html
_includes/components/header/logo.html
_includes/components/indicator/breadcrumbs.html
_includes/components/indicator/header.html
_includes/components/reportingstatus/reporting-status-by-goal.html
_includes/header.html
_includes/scripts.html
_includes/search.html

Testing instructions: The changes included in this PR are:
1. The aria-label for the mobile hamburger menu should be "Show navigation menu" when collapsed, and "Hide navigation menu" when expanded.
2. The aria-label of the search button should be "Site search".
3. The "Edit" button on indicator pages should now be "Edit Indicator"
4. The aria-labels on the map search buttons should be "Map search", "Show map search" and "Hide map search" respectively
In addition, this PR includes everything from the spreadsheet we developed in #1758 
Testing this PR requires using an sdg-translations branch in the data config: https://github.com/open-sdg/sdg-translations/pull/310. Eg:
```
translations:
- class: TranslationInputSdgTranslations
source: https://github.com/brockfanning/sdg-translations.git …
```

Clarify button labels

---

_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.yearSlider.js

This is my first contribution to open-sdg
I hope I do everything right...
Starting the map wit the most recent year (as @MoBosse implementet for his SDG 1.8.0)
Example Indicator: [https://christoph-lsn.github.io/MT_Site/2-1-1/](https://christoph-lsn.github.io/MT_Site/2-1-1/)
Q | A
--- | ---
Fixed issues | Fixes #1650 

Year-slider starts with the most recent year

---

_includes/components/indicator/metadata.html
_includes/components/indicator/sources-alt.html
docs/configuration.md

To test this, there will need to be a site configuration for `empty_metadata_placeholder_sources`, like this:
```
empty_metadata_placeholder_sources: Not available for this source
```
Note that this PR also fixes another bug that I just noticed related to link fields in sources (eg, source_url_1, etc.). When testing can you please confirm that the source link fields are working as expected?
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-empty-metadata-placeholder-sources/5-5-1/)
Fixed issues | Fixes #1848 

Use new site config/default for empty metadata placeholder for sources

---

.github/workflows/test-pull-requests.yml
_includes/head.html
_includes/meta-tags.html
docs/configuration.md
tests/features/MetaTags.feature
tests/site/_data/site_config.yml

This depends on a jekyll-open-sdg-plugins PR: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/150. So it would need a change to the Gemfile like this:
`gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'meta-tags'`
This PR includes documentation on the configuration. Here is an example of using it to add a meta description on the "/about" page:
```
meta_tags:
- path: about
name: description
content: my description content
```
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-meta-tags/)
Fixed issues | Fixes #1860 

Meta tag functionality

---

_includes/components/goal/goal-content.html
_includes/components/goal/header.html
_includes/title-tag.html
tests/features/Goal.feature
tests/features/LanguageSwitcher.feature
tests/site/_data/site_config.yml

Depends on a jekyll-open-sdg-plugins PR: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/149
* The "Gemfile" will need to point to the PR mentioned above, eg:
gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'goal-heading-per-goal'
* The site configuration will need the `heading` and/or `content_heading` in the `create_goals configuration, eg:
create_goals:
goals:
- heading: My custom heading for Goal 1
content_heading: My custom subheading for Goal 1
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-goal-heading-per-goal/)
Fixed issues | Fixes #1859 

Custom headings and subheadings for goal pages

---

docs/upgrades/upgrading-1-0-0.md

The links in the 1.0.0 upgrade instructions point to files which are very different now. This change "pins" them to older versions of the files.
Q | A
--- | ---

More accurate links in 1.0.0 upgrade instructions

---

_layouts/data-editor.html

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-data-editor-fix/)
Fixed issues | Fixes #1926 
To test this, the site configuration needs to have the data edit form enabled:
```
indicator_data_form:
enabled: true
```

Fix for "Edit data" indicator form

---

_includes/components/reportingstatus/reporting-status-overall.html
_layouts/reportingstatus.html
_sass/layouts/_reporting_status.scss
tests/features/Proxy.feature
tests/features/support/mink.js

This PR adds the SDG wheel as a decorative image in the first row of the reporting status and disaggregation status pages. This makes the horizontal bars line up with the others below it. The wheel should only show on the status-by-goal tabs -- not on any status-by-field tabs.
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-reportingstatus-overall-image/reporting-status/ - feature branch tested

SDG image on reporting status overall row

---

docs/indicator-configuration.md

This is an example of referencing a remotely-hosted image in the docs.

Example of screenshot in docs

---

_includes/assets/js/view/utils.js
_includes/components/contrast-toggle.html
_includes/components/download-all-data.html
_includes/components/indicator/headline.html

Two possible approach would have worked here:
1. Changing several <a> tags to <button> tags
2. Adding role=button to the <a> tags instead
In an ideal world, the first option is preferable, but would have required a lot of code rewriting. This PR does the easier approach of adding role=button in several places.
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-semantic-button-consistency/3-3-3/)
Fixed issues | Fixes #2031 

Use role=button in several places

---

.github/workflows/test-pull-requests.yml
tests/site/Gemfile

This doesn't change anything except that it uses Ruby 3 in the automated tests.

Use Ruby 3 in tests

---

_includes/assets/js/chartjs/accessibleCharts.js
_includes/assets/js/indicatorModel.js
_includes/assets/js/indicatorView.js
_includes/assets/js/mapView.js
_includes/assets/js/model/chartHelpers.js
_includes/assets/js/model/dataHelpers.js
_includes/assets/js/model/helpers.js
_includes/assets/js/model/tableHelpers.js
_includes/assets/js/model/utils.js
_includes/assets/js/plugins/jquery.sdgMap.js
_includes/assets/js/plugins/leaflet.disaggregationControls.js
_includes/assets/js/view/chartHelpers.js
_includes/assets/js/view/chartTypeBase.js
_includes/assets/js/view/dataHelpers.js
_includes/assets/js/view/fieldHelpers.js
_includes/assets/js/view/helpers.js
_includes/assets/js/view/tableHelpers.js
_includes/components/indicator/data-footer.html
docs/configuration.md
docs/data-configuration.md
tests/data/config_data.yml
tests/data/data/indicator_1-3-1.csv
tests/data/data/indicator_1-5-2.csv
tests/data/requirements.txt
tests/features/ObservationAttributes.feature
tests/site/_data/site_config.yml

This PR depends on a PR in sdg-build, and also depends on the latest translations in sdg-translations (for translation of the word "Note").
First, update the _config.yml file to point to the branch for remote_theme. For example instead of this:
```
remote_theme: open-sdg/open-sdg@2.2.0
```
Change it to:
```
remote_theme: brockfanning/open-sdg@observation-attributes
```
Next, in the site configuration file, add an `observation_attributes` section, like this:
```
observation_attributes:
- field: COMMENT_OBS
label: ''
```
First, update your requirements.txt file to point to the branch for sdg-build. For example instead of this:
```
git+https://github.com/open-sdg/sdg-build@2.2.0
```
Change it to this:
```
git+https://github.com/brockfanning/sdg-build-1@observation-attributes
```
Next, in …

Observation attributes (DON'T MERGE WITHOUT SQUASHING)

---

_includes/assets/js/model/chartHelpers.js
_includes/assets/js/model/dataHelpers.js
_includes/assets/js/model/utils.js
_includes/assets/js/view/chartHelpers.js
_includes/assets/js/view/chartTypeBase.js
_includes/components/charts/annotation_presets.js
tests/data/indicator-config/2-2-2.yml
tests/site/_data/site_config.yml

This fixes a few things:
1. The "position" option for labels -- previously we used values like "left", "right", "top", "bottom", but now Chart.js only supports "start", "end", and "center". So this adds some backwards compatibility for the old values.
2. The "fontColor" option for labels -- for some reason we were using "fontColor" instead of the correct "color". So this adds some backwards compatibility to support both "fontColor" and "color".
3. High-contrast annotations: The high-contrast colors were not actually "kicking in" when the contrast was changed. I assume that an upgrade of Chart.js broke that. So this fixes that.
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-chartjs-annotation-fixes/8-8-1/) …

Fixes for chart.js annotations

---

_includes/assets/js/model/fieldHelpers.js
_includes/assets/js/plugins/leaflet.disaggregationControls.js

Test a variety of indicators to make sure all working properly - ones with multiple series, units and make sure all the settings work and checkboxes update. what happens to the checkboxes as you change settings - anything unexpected?
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-keep-user-selections-on-unit-change/3-3-2/)
Fixed issues | Fixes #2012 

Ensure checkboxes don't stay checked when switching units.

---

_includes/components/indicator/metadata-panes.html
_includes/components/indicator/metadata-tabs.html
_layouts/indicator-iframe.html
docs/deployment.md
tests/features/Indicator.feature
tests/site/Gemfile

This PR (along with https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/159) create iframe-friendly versions of each indicator. The URLs of the iframe-friendly versions is the same, but with "-frame" at the end. For example the iframe-friendly version of `/1-1-1` would be `/1-1-1-iframe`.
The "iframe-friendly" part is that these new versions of the indicators do not include the sitewide header and footer. They do include other parts of the indicator pages, like the indicator header, and the metadata tabs, which in theory could be removed as well, if that is what folks prefer (let me know in the comments below). They also include usage of the Pym.js library which can be used to avoid vertical scrollbars on the iframe.
In your site repository's Gemfile, point to …

Indicator iframes

---

_sass/components/_maps.scss

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-map-disaggregation-max-width/)

Always limit width of disagg controls on map

---

_includes/assets/js/model/dataHelpers.js
tests/data/data/indicator_4-4-1.csv
tests/data/indicator-config/4-4-1.yml
tests/features/ObservationAttributes.feature
tests/features/Search.feature

Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-observation-attribute-with-headline-bug/1-5-1/)
Fixed issues | Fixes #2097

Remove observation attributes from edges data

---

_layouts/data-editor.html

This PR addresses a mistake made in the hotfix 2.3.1 - which broke the data download on the data edit form. This should be released as yet another hotfix (2.3.3) to fix the data edit form.

Fixes for deprecated ag-grid functionality to allow data download

---

docs/data-configuration.md
docs/translation.md
docs/tutorials/add-language.md

This is an overhaul of the translation documentation, with the purpose of simplifying and making things more clear by focusing only on a simple recommended approach.
Here is a markdown link for easier review: https://github.com/open-sdg/open-sdg/blob/955a368dd32da18ace6090e501bbb256a4098d4f/docs/translation.md

Docs translation updates

---

_includes/assets/js/indicatorModel.js
_includes/assets/js/model/fieldHelpers.js
_includes/assets/js/model/helpers.js
tests/data/data/indicator_2-3-1.csv
tests/features/StartValues.feature

This PR is intended to correct a regression caused by #2076. It hopefully covers the scenario that #2076 was addressing as well. This will unfortunately add some processing time when changing the series in an indicator that has starting values - but hopefully it is not noticeable or rare enough that it's OK.
Q | A
--- | ---
Fixed issues | Fixes #2154 
Related version | 2.4.0-dev

Use start values when changing series, unless there would be zero results
